/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.sistema.view;

import br.com.martinello.bd.matriz.control.ExtracaoTableController;
import br.com.martinello.bd.matriz.control.FilialController;
import br.com.martinello.bd.matriz.control.ParcelasExtracaoController;
import br.com.martinello.bd.matriz.model.domain.ConsultaModel;
import br.com.martinello.bd.matriz.model.domain.ExtracaoModel;
import br.com.martinello.bd.matriz.model.domain.FilialModel;
import br.com.martinello.bd.matriz.model.domain.ParcelaModel;
import br.com.martinello.componentesbasicos.paineis.JPStatus;
import br.com.martinello.componentesbasicos.paineis.TelaProcessamento;
import br.com.martinello.componentesbasicos.view.TelaPadrao;
import br.com.martinello.util.FixedLengthDocument;
import br.com.martinello.util.Utilitarios;
import br.com.martinello.util.excessoes.ErroSistemaException;
import com.towel.swing.table.ObjectTableModel;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author luiz.almeida
 */
public class TelaExtracaoManual extends TelaPadrao {

    public static String retornoExtracao;
    private boolean retornoConsulta;
    private int contFiltro;
    private ConsultaModel filtroConsulta;
    public List<ConsultaModel> lmotivoBaixaBvs, lmotivoInclusao, lmotivoBaixaSpc, lnaturezaRegistro, lnaturezaInclusao;
    public ExtracaoTableController extracaoTableController;
    public FilialController filiaisControler = new FilialController();
    public static List<FilialModel> lfiliaisModel = new ArrayList();
    private List<ParcelaModel> lParcelaManual;
    public List<ExtracaoModel> lExtracaoModel;
    public ExtracaoModel extracaoModel;
    public ParcelasExtracaoController parcelaExtracao;

    private final ObjectTableModel<ParcelaModel> otmParcelasManual = new ObjectTableModel<>(ParcelaModel.class, "pontoFilial,idParcela,numeroDoContrato,codCliente,cpfCnpj,nomeDoDevedor,situacaoDoCliente,"
            + "dataLancamento,dataVencimento,valorParcela,dataPagamento,capitalPago,situacaoParcela,dataNegativacao,dataBaixaNegativacao,dataAlteracao,avalista,codigoClientParcela");

    /**
     * Creates new form ExtracaoManual
     */
    public TelaExtracaoManual() {

        //super("Tela Extração Manual");
        initComponents();
        carregarFiliais();
        carregarFiltroEnvioManual();

        clsMotivoBaixaBvs.setVisible(false);
        clsMotivoBaixaSpc.setVisible(false);
        rMotivoBaixa.setVisible(false);
        rMotivoBaixaBvs.setVisible(false);

        paExtracaoManual.setEnabledAt(1, false);
        clsNaturezaBvs.setVisible(false);
        clsNaturezaSpc.setVisible(false);
        rNaturezaBvs.setVisible(false);
        rNaturezaSpc.setVisible(false);
        rIncluirAvalista.setVisible(false);
        clsIncluirAvalista.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPStatusExtracaoManual = new br.com.martinello.componentesbasicos.paineis.JPStatus();
        paExtracaoManual = new br.com.martinello.componentesbasicos.paineis.PainelAba();
        ppBuscaExtrManual = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        ppFiltroBuscaExtrManual = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        rFiltroFilial = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroNome = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroCpf = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroCodigoCliente = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroContrato = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroDataVencimento = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroDataPagamento = new br.com.martinello.componentesbasicos.Rotulo();
        clsFiltroFilial = new br.com.martinello.componentesbasicos.CampoListaSimples();
        cscFiltroNome = new br.com.martinello.componentesbasicos.consulta.CampoStringConsulta();
        ccccFiltroCpf = new br.com.martinello.componentesbasicos.consulta.CampoCpfCnpjConsulta();
        csFiltroCodigoCliente = new br.com.martinello.componentesbasicos.CampoString();
        csFiltroContrato = new br.com.martinello.componentesbasicos.CampoString();
        cdFiltroVencInicial = new br.com.martinello.componentesbasicos.CampoData();
        cdFiltroPagInicio = new br.com.martinello.componentesbasicos.CampoData();
        bFiltroPesquisar = new br.com.martinello.componentesbasicos.Botao();
        bFiltroExtrair = new br.com.martinello.componentesbasicos.Botao();
        cdFiltroVencFinal = new br.com.martinello.componentesbasicos.CampoData();
        cdFiltroPagFinal = new br.com.martinello.componentesbasicos.CampoData();
        bFiltroCancelar = new br.com.martinello.componentesbasicos.Botao();
        jspBuscaExtrManual = new javax.swing.JScrollPane();
        tpExtrManual = new br.com.martinello.componentesbasicos.TabelaPadrao();
        ppSalvarExtrManual = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        rNome = new br.com.martinello.componentesbasicos.Rotulo();
        rCPF = new br.com.martinello.componentesbasicos.Rotulo();
        rFilial = new br.com.martinello.componentesbasicos.Rotulo();
        rDataVencimento = new br.com.martinello.componentesbasicos.Rotulo();
        rDataLancamento = new br.com.martinello.componentesbasicos.Rotulo();
        rCodigoCliente = new br.com.martinello.componentesbasicos.Rotulo();
        rContrato = new br.com.martinello.componentesbasicos.Rotulo();
        rNaturezaBvs = new br.com.martinello.componentesbasicos.Rotulo();
        rMotivoBaixaBvs = new br.com.martinello.componentesbasicos.Rotulo();
        rValorParcela = new br.com.martinello.componentesbasicos.Rotulo();
        rNaturezaSpc = new br.com.martinello.componentesbasicos.Rotulo();
        rMotivoBaixa = new br.com.martinello.componentesbasicos.Rotulo();
        rCodigoAvalista = new br.com.martinello.componentesbasicos.Rotulo();
        rTipoRegistro = new br.com.martinello.componentesbasicos.Rotulo();
        rIncluirAvalista = new br.com.martinello.componentesbasicos.Rotulo();
        csFilial = new br.com.martinello.componentesbasicos.CampoString();
        csNome = new br.com.martinello.componentesbasicos.CampoString();
        cccCPF = new br.com.martinello.componentesbasicos.CampoCpfCnpj();
        csCodigoCliente = new br.com.martinello.componentesbasicos.CampoString();
        csCodigoAvalista = new br.com.martinello.componentesbasicos.CampoString();
        csContrato = new br.com.martinello.componentesbasicos.CampoString();
        csDataLancamento = new br.com.martinello.componentesbasicos.CampoString();
        csDataVencimento = new br.com.martinello.componentesbasicos.CampoString();
        clsNaturezaBvs = new br.com.martinello.componentesbasicos.CampoListaSimples();
        clsNaturezaSpc = new br.com.martinello.componentesbasicos.CampoListaSimples();
        clsMotivoBaixaBvs = new br.com.martinello.componentesbasicos.CampoListaSimples();
        clsMotivoBaixaSpc = new br.com.martinello.componentesbasicos.CampoListaSimples();
        clsTipoAcao = new br.com.martinello.componentesbasicos.CampoListaSimples();
        clsIncluirAvalista = new br.com.martinello.componentesbasicos.CampoListaSimples();
        bSalvar = new br.com.martinello.componentesbasicos.Botao();
        bCancelar = new br.com.martinello.componentesbasicos.Botao();
        cvValorParcela = new br.com.martinello.componentesbasicos.CampoValor();
        rCodigoContrato = new br.com.martinello.componentesbasicos.Rotulo();
        csCodigoContrato = new br.com.martinello.componentesbasicos.CampoString();
        rotulo1 = new br.com.martinello.componentesbasicos.Rotulo();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaObservacao = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Extração Individual");
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jPStatusExtracaoManual, java.awt.BorderLayout.PAGE_END);

        ppBuscaExtrManual.setLayout(new java.awt.BorderLayout());

        ppFiltroBuscaExtrManual.setPreferredSize(new java.awt.Dimension(1038, 150));

        rFiltroFilial.setText("Empresa:");

        rFiltroNome.setText("Nome:");

        rFiltroCpf.setText("CPF/CNPJ:");

        rFiltroCodigoCliente.setText("Código Cliente:");

        rFiltroContrato.setText("Contrato:");

        rFiltroDataVencimento.setText("Data Vencimento:");

        rFiltroDataPagamento.setText("Data Pagamento:");

        csFiltroCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csFiltroCodigoClienteActionPerformed(evt);
            }
        });

        cdFiltroVencInicial.setPreferredSize(null);

        cdFiltroPagInicio.setPreferredSize(null);

        bFiltroPesquisar.setText("Pesquisar");
        bFiltroPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltroPesquisarActionPerformed(evt);
            }
        });

        bFiltroExtrair.setText("Extrair");
        bFiltroExtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltroExtrairActionPerformed(evt);
            }
        });

        cdFiltroVencFinal.setPreferredSize(null);

        cdFiltroPagFinal.setPreferredSize(null);

        bFiltroCancelar.setText("Cancelar");
        bFiltroCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltroCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ppFiltroBuscaExtrManualLayout = new javax.swing.GroupLayout(ppFiltroBuscaExtrManual);
        ppFiltroBuscaExtrManual.setLayout(ppFiltroBuscaExtrManualLayout);
        ppFiltroBuscaExtrManualLayout.setHorizontalGroup(
            ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFiltroBuscaExtrManualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rFiltroFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clsFiltroFilial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cscFiltroNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ccccFiltroCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(csFiltroCodigoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(csFiltroContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppFiltroBuscaExtrManualLayout.createSequentialGroup()
                        .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rFiltroDataPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rFiltroDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cdFiltroPagInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cdFiltroVencInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cdFiltroVencFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdFiltroPagFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 397, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppFiltroBuscaExtrManualLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bFiltroExtrair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bFiltroCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bFiltroPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        ppFiltroBuscaExtrManualLayout.setVerticalGroup(
            ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFiltroBuscaExtrManualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rFiltroFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsFiltroFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdFiltroVencInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdFiltroVencFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cscFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdFiltroPagInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdFiltroPagFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rFiltroCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccccFiltroCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFiltroPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(csFiltroCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFiltroCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppFiltroBuscaExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rFiltroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csFiltroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFiltroExtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ppBuscaExtrManual.add(ppFiltroBuscaExtrManual, java.awt.BorderLayout.PAGE_START);

        tpExtrManual.setModel(otmParcelasManual);
        tpExtrManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpExtrManualMouseClicked(evt);
            }
        });
        jspBuscaExtrManual.setViewportView(tpExtrManual);

        ppBuscaExtrManual.add(jspBuscaExtrManual, java.awt.BorderLayout.CENTER);

        paExtracaoManual.addTab("Buscar", ppBuscaExtrManual);

        rNome.setText("Nome:");

        rCPF.setText("CPF/CNPJ:");

        rFilial.setText("Filial:");

        rDataVencimento.setText("Data Vencimento:");

        rDataLancamento.setText("Data Lançamento:");

        rCodigoCliente.setText("Código Cliente:");

        rContrato.setText("Contrato:");

        rNaturezaBvs.setText("Natureza da Incluzão BVS:");

        rMotivoBaixaBvs.setText("Motivo da Baixa BVS:");

        rValorParcela.setText("Valor:");

        rNaturezaSpc.setText("Natureza da Incluzão SPC:");

        rMotivoBaixa.setText("Motivo da Baixa SPC:");

        rCodigoAvalista.setText("Código Avalista:");

        rTipoRegistro.setText("Tipo:");

        rIncluirAvalista.setText("Incluir Avalista:");

        csFilial.setEditable(false);

        csNome.setEditable(false);

        cccCPF.setEditable(false);

        csCodigoCliente.setEditable(false);

        csCodigoAvalista.setEditable(false);

        csContrato.setEditable(false);

        csDataLancamento.setEditable(false);
        csDataLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csDataLancamentoActionPerformed(evt);
            }
        });

        csDataVencimento.setEditable(false);

        clsTipoAcao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inclusão", "Baixa", " " }));
        clsTipoAcao.setSelectedIndex(2);
        clsTipoAcao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                clsTipoAcaoFocusLost(evt);
            }
        });
        clsTipoAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsTipoAcaoActionPerformed(evt);
            }
        });

        clsIncluirAvalista.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));

        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        cvValorParcela.setEditable(false);

        rCodigoContrato.setText("Código Contrato:");

        csCodigoContrato.setEditable(false);

        rotulo1.setText("Observação:");

        jtaObservacao.setColumns(20);
        jtaObservacao.setDocument(new FixedLengthDocument(250));
        jtaObservacao.setLineWrap(true);
        jtaObservacao.setRows(5);
        jScrollPane2.setViewportView(jtaObservacao);

        javax.swing.GroupLayout ppSalvarExtrManualLayout = new javax.swing.GroupLayout(ppSalvarExtrManual);
        ppSalvarExtrManual.setLayout(ppSalvarExtrManualLayout);
        ppSalvarExtrManualLayout.setHorizontalGroup(
            ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppSalvarExtrManualLayout.createSequentialGroup()
                .addContainerGap(638, Short.MAX_VALUE)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(481, 481, 481))
            .addGroup(ppSalvarExtrManualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppSalvarExtrManualLayout.createSequentialGroup()
                        .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rIncluirAvalista, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rCodigoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rDataVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rDataLancamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rCodigoAvalista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rFilial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rCodigoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(csContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csNome, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csCodigoAvalista, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cccCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(csDataVencimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(csDataLancamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(csCodigoContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cvValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clsIncluirAvalista, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ppSalvarExtrManualLayout.createSequentialGroup()
                        .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rMotivoBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rMotivoBaixaBvs, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rNaturezaSpc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rNaturezaBvs, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clsMotivoBaixaBvs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clsNaturezaSpc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clsNaturezaBvs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clsMotivoBaixaSpc, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ppSalvarExtrManualLayout.createSequentialGroup()
                        .addComponent(rTipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clsTipoAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ppSalvarExtrManualLayout.createSequentialGroup()
                        .addComponent(rotulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ppSalvarExtrManualLayout.setVerticalGroup(
            ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppSalvarExtrManualLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cccCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCodigoAvalista, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csCodigoAvalista, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cvValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rCodigoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csCodigoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rTipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsTipoAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rNaturezaBvs, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsNaturezaBvs, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rNaturezaSpc, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsNaturezaSpc, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rMotivoBaixaBvs, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsMotivoBaixaBvs, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rMotivoBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsMotivoBaixaSpc, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rIncluirAvalista, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsIncluirAvalista, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(ppSalvarExtrManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        paExtracaoManual.addTab("Salvar Extração", ppSalvarExtrManual);

        getContentPane().add(paExtracaoManual, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void csFiltroCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csFiltroCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csFiltroCodigoClienteActionPerformed

    private void csDataLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csDataLancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csDataLancamentoActionPerformed

    private void bFiltroExtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltroExtrairActionPerformed
        //  carregarFiltroEnvioManual();
        extrairRegistro();
    }//GEN-LAST:event_bFiltroExtrairActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        int result;
        Object[] options = {"Confirmar", "Cancelar"};
        result = JOptionPane.showOptionDialog(null, "Será Extraido o registro de Modo Manual. \n Clique Confirmar Para Continuar!", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (result == 0) {

            parcelaExtracao = new ParcelasExtracaoController();
            extracaoModel = new ExtracaoModel();
            boolean lista = false;

            extracaoModel.setPontoFilial(csFilial.getText().substring(2));
            extracaoModel.setCodCliente(csCodigoCliente.getText());
            extracaoModel.setNumeroDoContrato(csContrato.getText());
            extracaoModel.setCodigoClientParcela(csCodigoContrato.getText());
            extracaoModel.setObservacao(jtaObservacao.getText());

            if (clsTipoAcao.getSelectedItem().toString().equals("Baixa")) {
                extracaoModel.setTipoParcela("B");
                if (clsMotivoBaixaBvs.getSelectedItem() != null) {
                    extracaoModel.setIdMotivoBaixaBvs(clsMotivoBaixaBvs.getSelectedItem().toString().replaceAll("[^0-9]", ""));
                    lista = true;

                } else {
                    jPStatusExtracaoManual.setStatus("Selecione o motivo da baixa facmat", JPStatus.ERRO);
                    lista = false;
                }
                if (clsMotivoBaixaSpc.getSelectedItem() != null) {
                    extracaoModel.setIdMotivoBaixaSpc(clsMotivoBaixaSpc.getSelectedItem().toString().replaceAll("[^0-9]", ""));
                    extracaoModel.setMotivoBaixaSpc(clsMotivoBaixaSpc.getSelectedItem().toString().replaceAll("[0-9,]", "").replace("-", "").toUpperCase().trim());
                    lista = true;
                } else {
                    jPStatusExtracaoManual.setStatus("Selecione o motivo da baixa SPC", JPStatus.ERRO);
                    lista = false;
                }

            } else {
                extracaoModel.setTipoParcela("I");
                if (clsIncluirAvalista.getString().toUpperCase().equals("SIM") && csCodigoAvalista.getString().trim().length() > 0) {
                    extracaoModel.setInsertAvalista("S");
                } else {
                    extracaoModel.setInsertAvalista("N");
                }
                if (clsNaturezaBvs.getSelectedItem() != null) {
                    extracaoModel.setIdNaturezaRegistroBvs(clsNaturezaBvs.getSelectedItem().toString().replaceAll("[^0-9]", ""));
                    extracaoModel.setMotivoInclusaoBvs("1");
                    lista = true;
                } else {
                    jPStatusExtracaoManual.setStatus("Selecione a natureza da inclusão facmat", JPStatus.ERRO);
                    lista = false;
                }
                if (clsNaturezaSpc.getSelectedItem() != null) {
                    extracaoModel.setIdNaturezaInclusaoSpc(clsNaturezaSpc.getSelectedItem().toString().replaceAll("[^0-9]", ""));
                    extracaoModel.setMotivoInclusaoSpc(clsNaturezaSpc.getSelectedItem().toString().replaceAll("[0-9,]", "").replace("-", "").toUpperCase().trim());
                    lista = true;
                } else {
                    jPStatusExtracaoManual.setStatus("Selecione a natureza da inclusão Spc", JPStatus.ERRO);
                    lista = false;;
                }
            }
            if (lista == true) {
                extracaoModel.setOrigemRegistro("M");
                retornoExtracao = "";
                for (FilialModel filial : lfiliaisModel) {
                    String nome = csFilial.getText().toString();
                    if (filial.getPontoFilial().equalsIgnoreCase(nome)) {
                        extracaoModel.setPontoFilial(filial.getFilialSgl());
                        extracaoModel.setCodfil(Integer.parseInt(filial.getCodFil()));
                        extracaoModel.setBdOrigem(filial.getOrigemBD());
                    }
                }

               
                try {
                    lExtracaoModel = new LinkedList<>();
                    lExtracaoModel.add(extracaoModel);
                    parcelaExtracao.realizarExtracao(lExtracaoModel, retornoExtracao);
                    jPStatusExtracaoManual.setStatus("Registro Nº " + extracaoModel.getNumeroDoContrato() + " Extraido com Sucesso!", JPStatus.ALERTA);
                    JOptionPane.showMessageDialog(null, "Registro Nº " + extracaoModel.getNumeroDoContrato() + " Extraido com Sucesso!", "Informação", JOptionPane.DEFAULT_OPTION);

                    paExtracaoManual.setSelectedIndex(0);
                    paExtracaoManual.setEnabledAt(1, false);
                } catch (ErroSistemaException ex) {
                    ex.printStackTrace();
                    jPStatusExtracaoManual.setStatus(ex.getMessage(), JPStatus.ERRO, ex);
                }

            } else {
                jPStatusExtracaoManual.setStatus("Não possível realizar a extração, verifique se os os campos foram selecionados corretamente!", JPStatus.ERRO);
            }

        }
    }//GEN-LAST:event_bSalvarActionPerformed

    private void bFiltroPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltroPesquisarActionPerformed
        buscarRegistro();
    }//GEN-LAST:event_bFiltroPesquisarActionPerformed

    private void bFiltroCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltroCancelarActionPerformed
        limparPesquisar();
    }//GEN-LAST:event_bFiltroCancelarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        limparSalvar();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void tpExtrManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpExtrManualMouseClicked
        if (evt.getClickCount() == 2) {
            extrairRegistro();
        }
    }//GEN-LAST:event_tpExtrManualMouseClicked

    private void clsTipoAcaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clsTipoAcaoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_clsTipoAcaoFocusLost

    private void clsTipoAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsTipoAcaoActionPerformed
        if (clsTipoAcao.getSelectedItem().toString().equalsIgnoreCase("Inclusão")) {
            clsMotivoBaixaBvs.setVisible(false);
            clsMotivoBaixaSpc.setVisible(false);
            rMotivoBaixa.setVisible(false);
            rMotivoBaixaBvs.setVisible(false);

            clsNaturezaBvs.setVisible(true);
            clsNaturezaSpc.setVisible(true);
            rNaturezaBvs.setVisible(true);
            rNaturezaSpc.setVisible(true);
            rIncluirAvalista.setVisible(true);
            clsIncluirAvalista.setVisible(true);
        } else {
            clsNaturezaBvs.setVisible(false);
            clsNaturezaSpc.setVisible(false);
            rNaturezaBvs.setVisible(false);
            rNaturezaSpc.setVisible(false);
            rIncluirAvalista.setVisible(false);
            clsIncluirAvalista.setVisible(false);
            clsMotivoBaixaBvs.setVisible(true);
            clsMotivoBaixaSpc.setVisible(true);
            rMotivoBaixa.setVisible(true);
            rMotivoBaixaBvs.setVisible(true);

        }
    }//GEN-LAST:event_clsTipoAcaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.componentesbasicos.Botao bCancelar;
    private br.com.martinello.componentesbasicos.Botao bFiltroCancelar;
    private br.com.martinello.componentesbasicos.Botao bFiltroExtrair;
    private br.com.martinello.componentesbasicos.Botao bFiltroPesquisar;
    private br.com.martinello.componentesbasicos.Botao bSalvar;
    private br.com.martinello.componentesbasicos.CampoCpfCnpj cccCPF;
    private br.com.martinello.componentesbasicos.consulta.CampoCpfCnpjConsulta ccccFiltroCpf;
    private br.com.martinello.componentesbasicos.CampoData cdFiltroPagFinal;
    private br.com.martinello.componentesbasicos.CampoData cdFiltroPagInicio;
    private br.com.martinello.componentesbasicos.CampoData cdFiltroVencFinal;
    private br.com.martinello.componentesbasicos.CampoData cdFiltroVencInicial;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsFiltroFilial;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsIncluirAvalista;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsMotivoBaixaBvs;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsMotivoBaixaSpc;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsNaturezaBvs;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsNaturezaSpc;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsTipoAcao;
    private br.com.martinello.componentesbasicos.CampoString csCodigoAvalista;
    private br.com.martinello.componentesbasicos.CampoString csCodigoCliente;
    private br.com.martinello.componentesbasicos.CampoString csCodigoContrato;
    private br.com.martinello.componentesbasicos.CampoString csContrato;
    private br.com.martinello.componentesbasicos.CampoString csDataLancamento;
    private br.com.martinello.componentesbasicos.CampoString csDataVencimento;
    private br.com.martinello.componentesbasicos.CampoString csFilial;
    private br.com.martinello.componentesbasicos.CampoString csFiltroCodigoCliente;
    private br.com.martinello.componentesbasicos.CampoString csFiltroContrato;
    private br.com.martinello.componentesbasicos.CampoString csNome;
    private br.com.martinello.componentesbasicos.consulta.CampoStringConsulta cscFiltroNome;
    private br.com.martinello.componentesbasicos.CampoValor cvValorParcela;
    private static br.com.martinello.componentesbasicos.paineis.JPStatus jPStatusExtracaoManual;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jspBuscaExtrManual;
    private javax.swing.JTextArea jtaObservacao;
    private br.com.martinello.componentesbasicos.paineis.PainelAba paExtracaoManual;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppBuscaExtrManual;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppFiltroBuscaExtrManual;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppSalvarExtrManual;
    private br.com.martinello.componentesbasicos.Rotulo rCPF;
    private br.com.martinello.componentesbasicos.Rotulo rCodigoAvalista;
    private br.com.martinello.componentesbasicos.Rotulo rCodigoCliente;
    private br.com.martinello.componentesbasicos.Rotulo rCodigoContrato;
    private br.com.martinello.componentesbasicos.Rotulo rContrato;
    private br.com.martinello.componentesbasicos.Rotulo rDataLancamento;
    private br.com.martinello.componentesbasicos.Rotulo rDataVencimento;
    private br.com.martinello.componentesbasicos.Rotulo rFilial;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroCodigoCliente;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroContrato;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroCpf;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroDataPagamento;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroDataVencimento;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroFilial;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroNome;
    private br.com.martinello.componentesbasicos.Rotulo rIncluirAvalista;
    private br.com.martinello.componentesbasicos.Rotulo rMotivoBaixa;
    private br.com.martinello.componentesbasicos.Rotulo rMotivoBaixaBvs;
    private br.com.martinello.componentesbasicos.Rotulo rNaturezaBvs;
    private br.com.martinello.componentesbasicos.Rotulo rNaturezaSpc;
    private br.com.martinello.componentesbasicos.Rotulo rNome;
    private br.com.martinello.componentesbasicos.Rotulo rTipoRegistro;
    private br.com.martinello.componentesbasicos.Rotulo rValorParcela;
    private br.com.martinello.componentesbasicos.Rotulo rotulo1;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpExtrManual;
    // End of variables declaration//GEN-END:variables
 private void carregarFiliais() {
        try {
            lfiliaisModel = filiaisControler.listarFilialController();
        } catch (ErroSistemaException ex) {
            jPStatusExtracaoManual.setStatus(ex.getLocalizedMessage(), JPStatus.ERRO, ex);
        }

        for (FilialModel filiais : lfiliaisModel) {
            clsFiltroFilial.addItem(filiais);
            //jcb_FiliaisExtracaoManual.addItem(filiais);
        }
    }

    private void carregarFiltroEnvioManual() {
        extracaoTableController = new ExtracaoTableController();
        lmotivoBaixaBvs = new ArrayList<>();
        try {
            lmotivoBaixaBvs = extracaoTableController.listarMotBaixaBvs();
        } catch (ErroSistemaException ex) {
            jPStatusExtracaoManual.setStatus(ex.getLocalizedMessage(), JPStatus.ERRO, ex);
        }
        for (ConsultaModel filtro1 : lmotivoBaixaBvs) {
            clsMotivoBaixaBvs.addItem(filtro1.getIdMotivoBaixaBvs() + " - " + filtro1.getMotivoBaixaBvs());
        }
        lmotivoBaixaSpc = new ArrayList<>();
        extracaoTableController = new ExtracaoTableController();
        try {
            lmotivoBaixaSpc = extracaoTableController.listarMotBaixaSpc();
        } catch (ErroSistemaException ex) {
            jPStatusExtracaoManual.setStatus(ex.getLocalizedMessage(), JPStatus.ERRO, ex);
        }
        for (ConsultaModel filtro2 : lmotivoBaixaSpc) {
            clsMotivoBaixaSpc.addItem(filtro2.getIdMotivoBaixaSpc() + " - " + filtro2.getMotivoBaixaSpc());
        }
        extracaoTableController = new ExtracaoTableController();
        lnaturezaInclusao = new ArrayList<>();
        try {
            lnaturezaInclusao = extracaoTableController.listarNaturezaInclusao();
        } catch (ErroSistemaException ex) {
            jPStatusExtracaoManual.setStatus(ex.getLocalizedMessage(), JPStatus.ERRO, ex);
        }
        for (ConsultaModel filtro3 : lnaturezaInclusao) {
            clsNaturezaSpc.addItem(filtro3.getIdNaturezaInclusaoSpc() + " - " + filtro3.getNaturezaInclusaoSpc());
        }
        extracaoTableController = new ExtracaoTableController();
        lnaturezaRegistro = new ArrayList<>();
        try {
            lnaturezaRegistro = extracaoTableController.listarNaturezaRegistro();
        } catch (ErroSistemaException ex) {
            jPStatusExtracaoManual.setStatus(ex.getLocalizedMessage(), JPStatus.ERRO, ex);
        }
        for (ConsultaModel filtro4 : lnaturezaRegistro) {
            clsNaturezaBvs.addItem(filtro4.getIdNaturezaRegistroBvs() + " - " + filtro4.getNaturezaRegistroBvs());
        }
        clsNaturezaBvs.setSelectedIndex(24);
        clsNaturezaSpc.setSelectedIndex(4);
        clsMotivoBaixaBvs.setSelectedIndex(0);
        clsMotivoBaixaSpc.setSelectedIndex(0);
    }

    private void limparSalvar() {
        csFilial.setText("");
        csNome.setText("");
        cccCPF.setText("");
        csCodigoCliente.setText("");
        csCodigoAvalista.setText("");
        csContrato.setText("");
        csDataLancamento.setText("");
        csDataVencimento.setText("");
        cvValorParcela.setDouble(null);
        csCodigoContrato.setText("");
        paExtracaoManual.setSelectedIndex(0);
        paExtracaoManual.setEnabledAt(1, false);

    }

    private void limparPesquisar() {
        csFiltroCodigoCliente.setText("");
        cscFiltroNome.setaValorFiltro("");
        csFiltroContrato.setText("");
        ccccFiltroCpf.setaValorFiltro("");
        cdFiltroVencInicial.setDate(null);
        cdFiltroPagFinal.setDate(null);
        cdFiltroPagInicio.setDate(null);
        cdFiltroVencFinal.setDate(null);
    }

    private boolean buscarRegistro() {
        // TODO add your handling code here:
        final TelaProcessamento telaProcessamento = new TelaProcessamento("Realizando consulta...");

        filtroConsulta = new ConsultaModel();
        if (clsFiltroFilial.getSelectedItem().toString().equals("TODAS")) {
            retornoConsulta = false;
            jPStatusExtracaoManual.setStatus("É necessário selecionar uma filial!", JPStatus.ERRO);
            return retornoConsulta;
        } else {
            for (FilialModel filial : lfiliaisModel) {
                String nome = clsFiltroFilial.getSelectedItem().toString();
                if (filial.getNomeLoja().equalsIgnoreCase(nome)) {
                    filtroConsulta.setPontoFilial(filial.getFilialSgl());
                    filtroConsulta.setOrigem_BD(filial.getOrigemBD());
                }
            }

            contFiltro++;
        }
        if (cscFiltroNome.getFiltroOld() != null) {
            filtroConsulta.setNome(cscFiltroNome.getFiltroOld().toUpperCase());
            contFiltro++;
        }
        if (csFiltroContrato.getText().equals("")) {

        } else {
            filtroConsulta.setNumeroDoContrato(csFiltroContrato.getText());
            contFiltro++;
        }
        if (csFiltroCodigoCliente.getText().equals("")) {

        } else {
            filtroConsulta.setCodCliente(csFiltroCodigoCliente.getText());
            contFiltro++;
        }
        String cpfCnpj = ccccFiltroCpf.getFiltroOld() != null ? ccccFiltroCpf.getFiltroOld().replaceAll("[^0-9]", "").trim() : "";
        if (cpfCnpj != null && !cpfCnpj.isEmpty()) {
            filtroConsulta.setCpfCnpj(cpfCnpj);
            contFiltro++;
        }
        if (cdFiltroVencInicial.getDate() != null) {
            if (cdFiltroVencFinal.getDate() != null) {
                filtroConsulta.setDataInicial(Utilitarios.converteDataString(cdFiltroVencInicial.getDate(), "dd/MM/yyyy"));
                contFiltro++;
            } else {
                jPStatusExtracaoManual.setStatus("O campo data vencimento precisa ser preenchido nos dois campos, por favor preencha o campo ao lado direito!", JPStatus.ALERTA, 20);
                return retornoConsulta = false;
            }
        }
        if (cdFiltroVencFinal.getDate() != null) {
            if (cdFiltroVencInicial.getDate() != null) {
                filtroConsulta.setDataFinal(Utilitarios.converteDataString(cdFiltroVencFinal.getDate(), "dd/MM/yyyy"));
                contFiltro++;
            } else {
                jPStatusExtracaoManual.setStatus("O campo data vencimento precisa ser preenchido nos dois campos, por favor preencha o campo ao lado esquerdo!", JPStatus.ALERTA, 20);
                return retornoConsulta = false;
            }
        }
        if (cdFiltroPagInicio.getDate() != null) {
            if (cdFiltroPagFinal.getDate() != null) {
                filtroConsulta.setDataIniciaPag(Utilitarios.converteDataString(cdFiltroPagInicio.getDate(), "dd/MM/yyyy"));
                contFiltro++;
            } else {
                jPStatusExtracaoManual.setStatus("O campo data pagamento precisa ser preenchido nos dois campos, por favor preencha o campo ao lado direito!", JPStatus.ALERTA, 20);
                return retornoConsulta = false;
            }

        }
        if (cdFiltroPagFinal.getDate() != null) {
            if (cdFiltroPagInicio.getDate() != null) {
                filtroConsulta.setDataFinalPag(Utilitarios.converteDataString(cdFiltroPagFinal.getDate(), "dd/MM/yyyy"));
                contFiltro++;
            } else {
                jPStatusExtracaoManual.setStatus("O campo data pagamento precisa ser preenchido nos dois campos, por favor preencha o campo ao lado esquerdo!", JPStatus.ALERTA, 20);
                return retornoConsulta = false;
            }

        }
        //filtroConsulta.setDbSapiens();
        new Thread() {
            @Override
            public void run() {
                lParcelaManual = new ArrayList<>();
                parcelaExtracao = new ParcelasExtracaoController();
                try {
                    lParcelaManual = parcelaExtracao.buscarExtracaoManual(filtroConsulta);
                } catch (ErroSistemaException ex) {
                    ex.printStackTrace();
                    jPStatusExtracaoManual.setStatus(retornoExtracao, JPStatus.ERRO, ex);
                }
                if (lParcelaManual == null) {
                    jPStatusExtracaoManual.setStatus("Nenhum resultado encontrado para a pesquisa refaça a busca", JPStatus.ERRO);
                } else {

                    otmParcelasManual.setData(lParcelaManual);

                    otmParcelasManual.fireTableDataChanged();
                    jPStatusExtracaoManual.setStatus("Pesquisa realizada com sucesso.", JPStatus.NORMAL);
                    if (tpExtrManual.getRowCount() > 0) {
                        tpExtrManual.packAll();
                        tpExtrManual.addRowSelectionInterval(tpExtrManual.convertRowIndexToView(0), tpExtrManual.convertRowIndexToView(0));
                        tpExtrManual.grabFocus();
                    }

                }
                SwingUtilities.invokeLater(() -> {
                    telaProcessamento.dispose();
                });
            }
        }.start();
        telaProcessamento.setVisible(true);
        telaProcessamento.requestFocusInWindow();

        return retornoConsulta;

    }

    public void extrairRegistro() {
        int linha = tpExtrManual.getSelectedRow();
        ParcelaModel parcelaManual = new ParcelaModel();

        if (linha < 0) {
            jPStatusExtracaoManual.setStatus("Nenhuma linha selecionada, por favor selecione uma linha", JPStatus.ALERTA);
        } else {
            csFilial.setText(otmParcelasManual.getValue(tpExtrManual.getLinhaSelecionada()).getPontoFilial());
            csNome.setText(otmParcelasManual.getValue(tpExtrManual.getLinhaSelecionada()).getNomeDoDevedor());
            cccCPF.setText(otmParcelasManual.getValue(tpExtrManual.getLinhaSelecionada()).getCpfCnpj());
            csCodigoCliente.setText(otmParcelasManual.getValue(tpExtrManual.getLinhaSelecionada()).getCodCliente());
            csCodigoAvalista.setText(otmParcelasManual.getValue(tpExtrManual.getLinhaSelecionada()).getAvalista());
            csContrato.setText(otmParcelasManual.getValue(tpExtrManual.getLinhaSelecionada()).getNumeroDoContrato());
            csDataLancamento.setText(otmParcelasManual.getValue(tpExtrManual.getLinhaSelecionada()).getDataLancamento().toString());
            csDataVencimento.setText(Utilitarios.converteDataString((Date) otmParcelasManual.getValue(tpExtrManual.getLinhaSelecionada()).getDataVencimento(), "dd/MM/yyyy"));
            cvValorParcela.setValue(otmParcelasManual.getValue(tpExtrManual.getLinhaSelecionada()).getValorParcela());
            csCodigoContrato.setText(otmParcelasManual.getValue(tpExtrManual.getLinhaSelecionada()).getCodigoClientParcela());
            paExtracaoManual.setSelectedComponent(ppSalvarExtrManual);
            paExtracaoManual.setEnabledAt(1, true);

        }

    }

    public void inserirObservacao() {

    }
}
