/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.sistema.view;

import br.com.martinello.bd.matriz.control.DiversosControl;
import br.com.martinello.componentesbasicos.view.TelaPadrao;
import br.com.martinello.util.excessoes.ErroSistemaException;

/**
 *
 * @author luiz.almeida
 */
public class TelaDiversos extends TelaPadrao {

   
    private DiversosControl diversosControl = new DiversosControl();

    /**
     * Creates new form TelaParametros
     */
  
  

    public TelaDiversos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ppTabelaParametros = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        jpsParametros = new br.com.martinello.componentesbasicos.paineis.JPStatus();
        ppFiltroParametros = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        rNomeParametro = new br.com.martinello.componentesbasicos.Rotulo();
        bPesquisar1 = new br.com.martinello.componentesbasicos.Botao();
        campoListaSimples1 = new br.com.martinello.componentesbasicos.CampoListaSimples();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Diversos");
        setPreferredSize(new java.awt.Dimension(1366, 768));

        ppTabelaParametros.setLayout(new java.awt.BorderLayout());
        ppTabelaParametros.add(jpsParametros, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(ppTabelaParametros, java.awt.BorderLayout.CENTER);

        rNomeParametro.setText("Nome do Processo:");

        bPesquisar1.setText("E140NFV");
        bPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ppFiltroParametrosLayout = new javax.swing.GroupLayout(ppFiltroParametros);
        ppFiltroParametros.setLayout(ppFiltroParametrosLayout);
        ppFiltroParametrosLayout.setHorizontalGroup(
            ppFiltroParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFiltroParametrosLayout.createSequentialGroup()
                .addComponent(rNomeParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoListaSimples1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 867, Short.MAX_VALUE)
                .addComponent(bPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ppFiltroParametrosLayout.setVerticalGroup(
            ppFiltroParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFiltroParametrosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ppFiltroParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rNomeParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoListaSimples1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(ppFiltroParametros, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisar1ActionPerformed
       diversosControl = new DiversosControl();
        try {
            diversosControl.AjustarE140NFV();
            System.out.println("Fim do Update");
        } catch (ErroSistemaException ex) {
            jpsParametros.setStatus(ex.getMessage(), jpsParametros.ERRO, ex);
        }
    }//GEN-LAST:event_bPesquisar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.componentesbasicos.Botao bPesquisar1;
    private br.com.martinello.componentesbasicos.CampoListaSimples campoListaSimples1;
    private br.com.martinello.componentesbasicos.paineis.JPStatus jpsParametros;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppFiltroParametros;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppTabelaParametros;
    private br.com.martinello.componentesbasicos.Rotulo rNomeParametro;
    // End of variables declaration//GEN-END:variables


   
}
