/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.sistema.view;

import br.com.martinello.bd.matriz.control.ParcelaController;
import br.com.martinello.bd.matriz.model.domain.ExtracaoTableModel;
import br.com.martinello.util.excessoes.ErroSistemaException;
import javax.swing.JOptionPane;

/**
 *
 * @author luiz.almeida
 */
public class TelaExtorno extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    /**
     * Creates new form TelaConsultaProduto
     *
     * @param parent
     * @param modal
     * @param campoConsultaProduto
     * @param extracaoModel
     */
    private static ExtracaoTableModel extracao;
    private static String origem;
    
    public TelaExtorno(java.awt.Frame parent, boolean modal, ExtracaoTableModel extracaoModel) {
        super(parent, modal);
        initComponents();
        carregarDados(extracaoModel);
        extracao = new ExtracaoTableModel();
        extracao = extracaoModel;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPadrao2 = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        bCancelar = new br.com.martinello.componentesbasicos.Botao();
        bSalvar = new br.com.martinello.componentesbasicos.Botao();
        jpsExtorno = new br.com.martinello.componentesbasicos.paineis.JPStatus();
        painelPadrao1 = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        rNome = new br.com.martinello.componentesbasicos.Rotulo();
        csNome = new br.com.martinello.componentesbasicos.CampoString();
        rCpf = new br.com.martinello.componentesbasicos.Rotulo();
        csCpf = new br.com.martinello.componentesbasicos.CampoString();
        csCodigoCliente = new br.com.martinello.componentesbasicos.CampoString();
        rCodigoCliente = new br.com.martinello.componentesbasicos.Rotulo();
        rFilial = new br.com.martinello.componentesbasicos.Rotulo();
        csFilial = new br.com.martinello.componentesbasicos.CampoString();
        csFilial1 = new br.com.martinello.componentesbasicos.CampoString();
        rCodFil = new br.com.martinello.componentesbasicos.Rotulo();
        rCidade = new br.com.martinello.componentesbasicos.Rotulo();
        csCidade = new br.com.martinello.componentesbasicos.CampoString();
        rCep = new br.com.martinello.componentesbasicos.Rotulo();
        ccpCep = new br.com.martinello.componentesbasicos.CampoCEP();
        csContrato = new br.com.martinello.componentesbasicos.CampoString();
        rContrato = new br.com.martinello.componentesbasicos.Rotulo();
        rValor = new br.com.martinello.componentesbasicos.Rotulo();
        rDataPagamento = new br.com.martinello.componentesbasicos.Rotulo();
        csvalor = new br.com.martinello.componentesbasicos.CampoString();
        cdDataPagamento = new br.com.martinello.componentesbasicos.CampoData();
        rSituacaoPago = new br.com.martinello.componentesbasicos.Rotulo();
        csSituacaoPagamento = new br.com.martinello.componentesbasicos.CampoString();
        rDataLancamento = new br.com.martinello.componentesbasicos.Rotulo();
        cdDataLancamento = new br.com.martinello.componentesbasicos.CampoData();
        cdDataVencimento = new br.com.martinello.componentesbasicos.CampoData();
        rDataVencimento = new br.com.martinello.componentesbasicos.Rotulo();
        rDataExtracao = new br.com.martinello.componentesbasicos.Rotulo();
        cdDataExtracao = new br.com.martinello.componentesbasicos.CampoData();
        cdDataNegativada = new br.com.martinello.componentesbasicos.CampoData();
        rDataNegativada = new br.com.martinello.componentesbasicos.Rotulo();
        rDataBaixa = new br.com.martinello.componentesbasicos.Rotulo();
        cdDataBaixa = new br.com.martinello.componentesbasicos.CampoData();
        jcbDataBaixa = new javax.swing.JCheckBox();
        jcbDataNegativacao = new javax.swing.JCheckBox();
        rotulo1 = new br.com.martinello.componentesbasicos.Rotulo();
        rotulo2 = new br.com.martinello.componentesbasicos.Rotulo();
        csNumTit = new br.com.martinello.componentesbasicos.CampoString();
        csCodTpt = new br.com.martinello.componentesbasicos.CampoString();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelPadrao2.setPreferredSize(new java.awt.Dimension(1350, 65));

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bSalvar.setText("Salvar/Alterar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPadrao2Layout = new javax.swing.GroupLayout(painelPadrao2);
        painelPadrao2.setLayout(painelPadrao2Layout);
        painelPadrao2Layout.setHorizontalGroup(
            painelPadrao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPadrao2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(649, 649, 649))
            .addGroup(painelPadrao2Layout.createSequentialGroup()
                .addComponent(jpsExtorno, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPadrao2Layout.setVerticalGroup(
            painelPadrao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPadrao2Layout.createSequentialGroup()
                .addComponent(jpsExtorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(painelPadrao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        getContentPane().add(painelPadrao2, java.awt.BorderLayout.SOUTH);

        rNome.setText("Nome:");

        csNome.setEnabled(false);

        rCpf.setText("Cpf:");

        csCpf.setEnabled(false);

        csCodigoCliente.setEnabled(false);

        rCodigoCliente.setText("Código Cliente:");

        rFilial.setText("Filial:");

        csFilial.setEnabled(false);

        csFilial1.setEnabled(false);

        rCodFil.setText("CodFil:");

        rCidade.setText("Cidade:");

        csCidade.setEnabled(false);

        rCep.setText("Cep:");

        ccpCep.setEnabled(false);

        csContrato.setEnabled(false);

        rContrato.setText("Contrato:");

        rValor.setText("Valor:");

        rDataPagamento.setText("Data Pagamento:");

        csvalor.setEnabled(false);

        cdDataPagamento.setEnabled(false);

        rSituacaoPago.setText("Pago:");

        csSituacaoPagamento.setEnabled(false);

        rDataLancamento.setText("Data Lançamento:");

        cdDataLancamento.setEnabled(false);

        cdDataVencimento.setEnabled(false);

        rDataVencimento.setText("Data Vencimento:");

        rDataExtracao.setText("Data Extração:");

        cdDataExtracao.setEnabled(false);

        cdDataNegativada.setEnabled(false);

        rDataNegativada.setText("Data Negativada:");

        rDataBaixa.setText("Data Baixa:");

        cdDataBaixa.setToolTipText("A data da baixa para extorno precisa ser = '31/12/1900'");
        cdDataBaixa.setEnabled(false);

        jcbDataBaixa.setText("Alterar");
        jcbDataBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDataBaixaActionPerformed(evt);
            }
        });

        jcbDataNegativacao.setText("Alterar");
        jcbDataNegativacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDataNegativacaoActionPerformed(evt);
            }
        });

        rotulo1.setText("NumTit:");

        rotulo2.setText("CodTpt:");

        csNumTit.setEnabled(false);

        csCodTpt.setEnabled(false);

        javax.swing.GroupLayout painelPadrao1Layout = new javax.swing.GroupLayout(painelPadrao1);
        painelPadrao1.setLayout(painelPadrao1Layout);
        painelPadrao1Layout.setHorizontalGroup(
            painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPadrao1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPadrao1Layout.createSequentialGroup()
                        .addComponent(rNome, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(csNome, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPadrao1Layout.createSequentialGroup()
                        .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(csCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelPadrao1Layout.createSequentialGroup()
                        .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rDataBaixa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(rContrato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(rValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(rDataPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(rSituacaoPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(rDataExtracao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(rDataNegativada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(rDataLancamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(rDataVencimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(rotulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rotulo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(csvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csSituacaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelPadrao1Layout.createSequentialGroup()
                                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cdDataBaixa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cdDataNegativada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbDataBaixa)
                                    .addComponent(jcbDataNegativacao)))
                            .addComponent(cdDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdDataExtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(csCodTpt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(csNumTit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(csContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                    .addGroup(painelPadrao1Layout.createSequentialGroup()
                        .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rCep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(csCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccpCep, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelPadrao1Layout.createSequentialGroup()
                        .addComponent(rCodFil, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(csFilial1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(731, Short.MAX_VALUE))
        );
        painelPadrao1Layout.setVerticalGroup(
            painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPadrao1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rCodFil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csFilial1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(csCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCep, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccpCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csNumTit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csCodTpt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rValor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSituacaoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csSituacaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataExtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdDataExtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataNegativada, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdDataNegativada, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbDataNegativacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPadrao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rDataBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cdDataBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbDataBaixa))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(painelPadrao1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        extornarContasReceber(extracao);
        JOptionPane.showMessageDialog(null, "Registro alterado com sucesso!", "Informação", JOptionPane.DEFAULT_OPTION);
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }
        dispose();

    }//GEN-LAST:event_bSalvarActionPerformed

    private void jcbDataBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDataBaixaActionPerformed
        if (jcbDataBaixa.isSelected()) {
            cdDataBaixa.setEnabled(true);
            origem = "Baixa";
        } else {
            cdDataBaixa.setEnabled(false);
        }
    }//GEN-LAST:event_jcbDataBaixaActionPerformed

    private void jcbDataNegativacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDataNegativacaoActionPerformed
        if (jcbDataNegativacao.isSelected()) {
            cdDataNegativada.setEnabled(true);
            origem = "Inclusao";
        } else {
            cdDataNegativada.setEnabled(false);
        }
    }//GEN-LAST:event_jcbDataNegativacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExtorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExtorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExtorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExtorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaExtorno dialog = new TelaExtorno(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.componentesbasicos.Botao bCancelar;
    private br.com.martinello.componentesbasicos.Botao bSalvar;
    private br.com.martinello.componentesbasicos.CampoCEP ccpCep;
    private br.com.martinello.componentesbasicos.CampoData cdDataBaixa;
    private br.com.martinello.componentesbasicos.CampoData cdDataExtracao;
    private br.com.martinello.componentesbasicos.CampoData cdDataLancamento;
    private br.com.martinello.componentesbasicos.CampoData cdDataNegativada;
    private br.com.martinello.componentesbasicos.CampoData cdDataPagamento;
    private br.com.martinello.componentesbasicos.CampoData cdDataVencimento;
    private br.com.martinello.componentesbasicos.CampoString csCidade;
    private br.com.martinello.componentesbasicos.CampoString csCodTpt;
    private br.com.martinello.componentesbasicos.CampoString csCodigoCliente;
    private br.com.martinello.componentesbasicos.CampoString csContrato;
    private br.com.martinello.componentesbasicos.CampoString csCpf;
    private br.com.martinello.componentesbasicos.CampoString csFilial;
    private br.com.martinello.componentesbasicos.CampoString csFilial1;
    private br.com.martinello.componentesbasicos.CampoString csNome;
    private br.com.martinello.componentesbasicos.CampoString csNumTit;
    private br.com.martinello.componentesbasicos.CampoString csSituacaoPagamento;
    private br.com.martinello.componentesbasicos.CampoString csvalor;
    private javax.swing.JCheckBox jcbDataBaixa;
    private javax.swing.JCheckBox jcbDataNegativacao;
    private br.com.martinello.componentesbasicos.paineis.JPStatus jpsExtorno;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao painelPadrao1;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao painelPadrao2;
    private br.com.martinello.componentesbasicos.Rotulo rCep;
    private br.com.martinello.componentesbasicos.Rotulo rCidade;
    private br.com.martinello.componentesbasicos.Rotulo rCodFil;
    private br.com.martinello.componentesbasicos.Rotulo rCodigoCliente;
    private br.com.martinello.componentesbasicos.Rotulo rContrato;
    private br.com.martinello.componentesbasicos.Rotulo rCpf;
    private br.com.martinello.componentesbasicos.Rotulo rDataBaixa;
    private br.com.martinello.componentesbasicos.Rotulo rDataExtracao;
    private br.com.martinello.componentesbasicos.Rotulo rDataLancamento;
    private br.com.martinello.componentesbasicos.Rotulo rDataNegativada;
    private br.com.martinello.componentesbasicos.Rotulo rDataPagamento;
    private br.com.martinello.componentesbasicos.Rotulo rDataVencimento;
    private br.com.martinello.componentesbasicos.Rotulo rFilial;
    private br.com.martinello.componentesbasicos.Rotulo rNome;
    private br.com.martinello.componentesbasicos.Rotulo rSituacaoPago;
    private br.com.martinello.componentesbasicos.Rotulo rValor;
    private br.com.martinello.componentesbasicos.Rotulo rotulo1;
    private br.com.martinello.componentesbasicos.Rotulo rotulo2;
    // End of variables declaration//GEN-END:variables
 private void extornarContasReceber(ExtracaoTableModel extracaoModel) {
        ParcelaController parcela = new ParcelaController();
        
        extracaoModel.setDataBaixa(cdDataBaixa.getDate());
        extracaoModel.setDataNegativada(cdDataNegativada.getDate());
        
        try {
            if (extracaoModel.getOrigemBd().equalsIgnoreCase("SGL")) {
                parcela.ExtornoContasReceber(extracaoModel);
            }
            if (extracaoModel.getOrigemBd().equalsIgnoreCase("NOVO_SGL")) {
                if (csCodTpt.getText().equals("") || csNumTit.getText().equals("")) {
                    throw new ErroSistemaException("Por favor Informar O numero do Titulo e o código do Tipo de Titulo!");
                } else {
                    extracaoModel.setNumtit(csNumTit.getText().trim());
                    extracaoModel.setCodTpt(csCodTpt.getText().trim());
                    parcela.ExtornoE301TCR(extracaoModel, origem);
                }
            }
            
        } catch (ErroSistemaException ex) {
            ex.printStackTrace();
            jpsExtorno.setStatus(ex.getMessage(), jpsExtorno.ERRO, ex);
        }
    }
    
    private void carregarDados(ExtracaoTableModel extracaoModel) {
        csNome.setText(extracaoModel.getNome());
        csCpf.setText(extracaoModel.getCpfCnpj());
        csCidade.setText(extracaoModel.getCidade());
        csFilial.setText(extracaoModel.getIdFilial());
        ccpCep.setText(extracaoModel.getCep());
        csvalor.setText("" + extracaoModel.getValor());
        csSituacaoPagamento.setText(extracaoModel.getPago());
        csContrato.setText(extracaoModel.getNumeroDoc());
        csNumTit.setText(extracaoModel.getNumtit());
        csCodTpt.setText(extracaoModel.getCodTpt());
        csCodigoCliente.setText(extracaoModel.getCodigoCliente());
        cdDataExtracao.setDate(extracaoModel.getDataExtracao());
        cdDataLancamento.setDate(extracaoModel.getDataLancamento());
        cdDataPagamento.setDate(extracaoModel.getDataPagamento());
        cdDataVencimento.setDate(extracaoModel.getDataVencimento());
        cdDataBaixa.setDate(extracaoModel.getDataBaixa());
        cdDataNegativada.setDate(extracaoModel.getDataNegativada());
        if (extracaoModel.getOrigemBd().equalsIgnoreCase("NOVO_SGL")) {
            csNumTit.setEnabled(true);
            csCodTpt.setEnabled(true);
        }
    }
}
