/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.sistema.view;

import br.com.martinello.bd.matriz.control.FilialController;
import br.com.martinello.bd.matriz.control.ImpcdlController;
import br.com.martinello.bd.matriz.model.domain.FilialModel;
import br.com.martinello.bd.matriz.model.domain.ImpcdlModel;
import br.com.martinello.componentesbasicos.paineis.JPStatus;
import br.com.martinello.componentesbasicos.paineis.TelaProcessamento;
import br.com.martinello.componentesbasicos.view.TelaPadrao;
import br.com.martinello.util.Utilitarios;
import br.com.martinello.util.excessoes.ErroSistemaException;
import com.towel.swing.table.ObjectTableModel;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author luiz.almeida
 */
public class TelaRegistroImportado extends TelaPadrao {

    private List<ImpcdlModel> LImpcdl = new ArrayList<>();
    private ImpcdlController impcdlControl = new ImpcdlController();
    final ObjectTableModel<ImpcdlModel> otmImpcdl = new ObjectTableModel<>(ImpcdlModel.class, "indice,impcdlId,provedor,impcdlContratoDigitado,impcdlContratoReal,impcdlFilial,impcdlCpf,impcdlDataNascimento,impcdlConsumidor,impcdlTipoDevedor,impcdlValor,impcdlDataVencimento,impcdlDataInclusao,impcdlDataCompra,impcdlDataExclusao,dataEncontrado,status,impcdlBairro,impcdlCidade,impcdlUf,impcdlCep,nomePai,nomeMae,logradouro");

    /**
     * Creates new form TelaAlteracaoRegistro
     */
    public TelaRegistroImportado() {

        initComponents();
        carregarFiliais();
        paRelacionados.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paRelacionados = new br.com.martinello.componentesbasicos.paineis.PainelAba();
        ppRegistrosImportados = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        ppFiltroRegistros = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        rFiltroFilial = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroNome = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroStatus = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroRegistroEncontrado = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroContratoReal = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroCpf = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroVencimento = new br.com.martinello.componentesbasicos.Rotulo();
        rFiltroDataEncontrado = new br.com.martinello.componentesbasicos.Rotulo();
        clsFiltroFilial = new br.com.martinello.componentesbasicos.CampoListaSimples();
        cscFiltroNome = new br.com.martinello.componentesbasicos.consulta.CampoStringConsulta();
        clsFiltroStatus = new br.com.martinello.componentesbasicos.CampoListaSimples();
        clsFiltroRegistroEncontrado = new br.com.martinello.componentesbasicos.CampoListaSimples();
        csFiltroContratoReal = new br.com.martinello.componentesbasicos.CampoString();
        cdDataVencimentoInicio = new br.com.martinello.componentesbasicos.CampoData();
        cdDataVencimentoFim = new br.com.martinello.componentesbasicos.CampoData();
        cdDataEncontrado = new br.com.martinello.componentesbasicos.CampoData();
        bFiltroPesquisar = new br.com.martinello.componentesbasicos.Botao();
        bFiltroCancelar = new br.com.martinello.componentesbasicos.Botao();
        bFiltroGerarExcel = new br.com.martinello.componentesbasicos.Botao();
        bFiltroAjuda = new br.com.martinello.componentesbasicos.Botao();
        bFiltroAlterar = new br.com.martinello.componentesbasicos.Botao();
        cccCpfCnpj = new br.com.martinello.componentesbasicos.consulta.CampoCpfCnpjConsulta();
        ppRegistros = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        jspRegistros = new javax.swing.JScrollPane();
        tpRegistrosImportados = new br.com.martinello.componentesbasicos.TabelaPadrao();
        ppAlterarRelacionado = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        bSalvar = new br.com.martinello.componentesbasicos.Botao();
        bCancelar = new br.com.martinello.componentesbasicos.Botao();
        rInformacoes = new br.com.martinello.componentesbasicos.Rotulo();
        rNomeFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rCpfFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rDataNascimentoFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rRGFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RNomeFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RCpfFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RDataNascimentoFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RRGFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rEnderecoFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rLogradouroFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rBairroFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rNumEndFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rCidadeFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rUFFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rCepFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RLogradouroFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RBairroFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RNumEndFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RCidadeFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RUFFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RCepFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rParcelas = new br.com.martinello.componentesbasicos.Rotulo();
        rFilialFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rContratoFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rClienteFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rValorFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rSituacaoFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rVencimentoFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        RFilialFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RClienteFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RSituacaoFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RValorFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RDataVencFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RContratoFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rContratoDigitadoFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rContratoRelacionadoFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rStatusFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        csContratoDigitadoFiltroAlterar = new br.com.martinello.componentesbasicos.CampoString();
        csContratoRelacionadoFiltroAlterar = new br.com.martinello.componentesbasicos.CampoString();
        RStatusFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rIdRegistroFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        RIdRegistroFiltroAlterar = new br.com.martinello.componentesbasicos.Rotulo();
        rProvedor = new br.com.martinello.componentesbasicos.Rotulo();
        RProvedor = new br.com.martinello.componentesbasicos.Rotulo();
        jcbContratoDigitado = new javax.swing.JCheckBox();
        jcbContratoReal = new javax.swing.JCheckBox();
        jpsRelacionados = new br.com.martinello.componentesbasicos.paineis.JPStatus();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registros Importados");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(1366, 768));

        ppRegistrosImportados.setLayout(new java.awt.BorderLayout());

        ppFiltroRegistros.setPreferredSize(new java.awt.Dimension(1225, 180));

        rFiltroFilial.setText("Filial:");

        rFiltroNome.setText("Nome:");

        rFiltroStatus.setText("Status:");

        rFiltroRegistroEncontrado.setText("Registro encontrado:");

        rFiltroContratoReal.setText("Contrato Real:");

        rFiltroCpf.setText("CPF/CNPJ:");

        rFiltroVencimento.setText("Vencimento:");

        rFiltroDataEncontrado.setText("Data Encontrado:");

        clsFiltroStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Importado", "Baixado", "Prescrito", "Aguardando", " " }));
        clsFiltroStatus.setSelectedIndex(4);

        clsFiltroRegistroEncontrado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim", "" }));
        clsFiltroRegistroEncontrado.setSelectedIndex(2);
        clsFiltroRegistroEncontrado.setToolTipText("");

        bFiltroPesquisar.setText("Pesquisar");
        bFiltroPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltroPesquisarActionPerformed(evt);
            }
        });

        bFiltroCancelar.setText("Cancelar");
        bFiltroCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltroCancelarActionPerformed(evt);
            }
        });

        bFiltroGerarExcel.setText("Gerar excel");

        bFiltroAjuda.setText("Ajuda");

        bFiltroAlterar.setText("Alterar");
        bFiltroAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltroAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ppFiltroRegistrosLayout = new javax.swing.GroupLayout(ppFiltroRegistros);
        ppFiltroRegistros.setLayout(ppFiltroRegistrosLayout);
        ppFiltroRegistrosLayout.setHorizontalGroup(
            ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFiltroRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rFiltroContratoReal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroRegistroEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cscFiltroNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clsFiltroFilial, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(clsFiltroRegistroEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csFiltroContratoReal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cccCpfCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rFiltroDataEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rFiltroVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdDataEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ppFiltroRegistrosLayout.createSequentialGroup()
                        .addComponent(cdDataVencimentoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cdDataVencimentoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bFiltroPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFiltroGerarExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFiltroCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFiltroAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ppFiltroRegistrosLayout.setVerticalGroup(
            ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppFiltroRegistrosLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppFiltroRegistrosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ppFiltroRegistrosLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(bFiltroPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ppFiltroRegistrosLayout.createSequentialGroup()
                                .addComponent(bFiltroGerarExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bFiltroCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bFiltroAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppFiltroRegistrosLayout.createSequentialGroup()
                        .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rFiltroFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clsFiltroFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rFiltroVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdDataVencimentoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdDataVencimentoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cscFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rFiltroDataEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdDataEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clsFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rFiltroRegistroEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clsFiltroRegistroEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rFiltroContratoReal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csFiltroContratoReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppFiltroRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rFiltroCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cccCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        ppRegistrosImportados.add(ppFiltroRegistros, java.awt.BorderLayout.NORTH);

        ppRegistros.setLayout(new java.awt.BorderLayout());

        tpRegistrosImportados.setModel(otmImpcdl);
        tpRegistrosImportados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpRegistrosImportadosMouseClicked(evt);
            }
        });
        jspRegistros.setViewportView(tpRegistrosImportados);

        ppRegistros.add(jspRegistros, java.awt.BorderLayout.CENTER);

        ppRegistrosImportados.add(ppRegistros, java.awt.BorderLayout.CENTER);

        paRelacionados.addTab("Relacionados", ppRegistrosImportados);

        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        rInformacoes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rInformacoes.setText("Informações do Cliente");

        rNomeFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rNomeFiltroAlterar.setText("Nome");

        rCpfFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rCpfFiltroAlterar.setText("Cpf/Cnpj");

        rDataNascimentoFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rDataNascimentoFiltroAlterar.setText("Data Nascimento");

        rRGFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rRGFiltroAlterar.setText("N° RG");

        RNomeFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        RRGFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rEnderecoFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rEnderecoFiltroAlterar.setText("Endereço");

        rLogradouroFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rLogradouroFiltroAlterar.setText("Logradouro");

        rBairroFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rBairroFiltroAlterar.setText("Bairro");

        rNumEndFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rNumEndFiltroAlterar.setText("N°");

        rCidadeFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rCidadeFiltroAlterar.setText("Cidade");

        rUFFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rUFFiltroAlterar.setText("UF");

        rCepFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rCepFiltroAlterar.setText("CEP");

        RLogradouroFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        RBairroFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        RNumEndFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        RCidadeFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        RUFFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        RCepFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rParcelas.setText("Parcela");

        rFilialFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rFilialFiltroAlterar.setText("Filial");

        rContratoFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rContratoFiltroAlterar.setText("Contrato");

        rClienteFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rClienteFiltroAlterar.setText("Cliente");

        rValorFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rValorFiltroAlterar.setText("Valor");

        rSituacaoFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSituacaoFiltroAlterar.setText("Situação");

        rVencimentoFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rVencimentoFiltroAlterar.setText("Data Vencimento");

        RFilialFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        RClienteFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        RSituacaoFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        RValorFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        RDataVencFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        RContratoFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rContratoDigitadoFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rContratoDigitadoFiltroAlterar.setText("Contrato Digitado");

        rContratoRelacionadoFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rContratoRelacionadoFiltroAlterar.setText("Contrato Relacionado");

        rStatusFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rStatusFiltroAlterar.setText("Status");

        csContratoDigitadoFiltroAlterar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        csContratoRelacionadoFiltroAlterar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        RStatusFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rIdRegistroFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rIdRegistroFiltroAlterar.setText("Id Registro");

        RIdRegistroFiltroAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rProvedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rProvedor.setText("Provedor");

        RProvedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jcbContratoDigitado.setText("Alterar");
        jcbContratoDigitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbContratoDigitadoActionPerformed(evt);
            }
        });

        jcbContratoReal.setText("Alterar");
        jcbContratoReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbContratoRealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ppAlterarRelacionadoLayout = new javax.swing.GroupLayout(ppAlterarRelacionado);
        ppAlterarRelacionado.setLayout(ppAlterarRelacionadoLayout);
        ppAlterarRelacionadoLayout.setHorizontalGroup(
            ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rNomeFiltroAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(RNomeFiltroAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RCpfFiltroAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rCpfFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                                .addComponent(rDataNascimentoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(rRGFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                                .addComponent(RDataNascimentoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(RRGFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(168, 168, 168))
                    .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RLogradouroFiltroAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rLogradouroFiltroAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rBairroFiltroAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(RBairroFiltroAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RNumEndFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rNumEndFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rCidadeFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RCidadeFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rCepFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RCepFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rUFFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RUFFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(rParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rEnderecoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rFilialFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RFilialFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rContratoDigitadoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(csContratoDigitadoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RContratoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rContratoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(61, 61, 61)
                                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rClienteFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RClienteFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rSituacaoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RSituacaoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(62, 62, 62)
                                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RDataVencFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rVencimentoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RValorFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rValorFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbContratoDigitado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(csContratoRelacionadoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rContratoRelacionadoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbContratoReal)
                                        .addGap(18, 18, 18)
                                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RStatusFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rStatusFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(rIdRegistroFiltroAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(RIdRegistroFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(97, 97, 97)
                                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(rProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(RProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap(124, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppAlterarRelacionadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(505, 505, 505))
        );
        ppAlterarRelacionadoLayout.setVerticalGroup(
            ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppAlterarRelacionadoLayout.createSequentialGroup()
                .addComponent(rInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rNomeFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rDataNascimentoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rRGFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RNomeFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RRGFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDataNascimentoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                        .addComponent(rCpfFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RCpfFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rEnderecoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                        .addComponent(rUFFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RUFFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rLogradouroFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rBairroFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rNumEndFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RLogradouroFiltroAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RBairroFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(RNumEndFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                                .addComponent(rCidadeFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RCidadeFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                                .addComponent(rCepFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RCepFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppAlterarRelacionadoLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rContratoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(RContratoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RSituacaoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RFilialFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RClienteFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(rFilialFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rClienteFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSituacaoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rVencimentoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rValorFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ppAlterarRelacionadoLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RValorFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDataVencFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68)
                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rContratoDigitadoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rContratoRelacionadoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rStatusFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rIdRegistroFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(csContratoDigitadoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbContratoDigitado)
                    .addComponent(csContratoRelacionadoFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbContratoReal)
                    .addComponent(RStatusFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RIdRegistroFiltroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addGroup(ppAlterarRelacionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        paRelacionados.addTab("Alterar", ppAlterarRelacionado);

        getContentPane().add(paRelacionados, java.awt.BorderLayout.CENTER);
        getContentPane().add(jpsRelacionados, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bFiltroPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltroPesquisarActionPerformed
        buscarImpcdl();
    }//GEN-LAST:event_bFiltroPesquisarActionPerformed

    private void bFiltroAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltroAlterarActionPerformed
        alterarRegistro();
    }//GEN-LAST:event_bFiltroAlterarActionPerformed

    private void tpRegistrosImportadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpRegistrosImportadosMouseClicked
        if (evt.getClickCount() == 2) {
            alterarRegistro();
        }
    }//GEN-LAST:event_tpRegistrosImportadosMouseClicked

    private void bFiltroCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltroCancelarActionPerformed
        limpar();
    }//GEN-LAST:event_bFiltroCancelarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        limparAlterar();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        int result;
        Object[] options = {"Confirmar", "Cancelar"};
        result = JOptionPane.showOptionDialog(null, "Será Modificado o contrato relacioanado. \n Clique Confirmar Para Continuar!", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (result == 0) {
            alterarRelacionado();
        }
        limparAlterar();
    }//GEN-LAST:event_bSalvarActionPerformed

    private void jcbContratoRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbContratoRealActionPerformed
        if (jcbContratoReal.isSelected()) {
            csContratoRelacionadoFiltroAlterar.setEnabled(true);
        } else {
            csContratoRelacionadoFiltroAlterar.setEnabled(false);
        }
    }//GEN-LAST:event_jcbContratoRealActionPerformed

    private void jcbContratoDigitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbContratoDigitadoActionPerformed
        if (jcbContratoDigitado.isSelected()) {
            csContratoDigitadoFiltroAlterar.setEnabled(true);
        } else {
            csContratoDigitadoFiltroAlterar.setEnabled(false);
        }
    }//GEN-LAST:event_jcbContratoDigitadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.componentesbasicos.Rotulo RBairroFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RCepFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RCidadeFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RClienteFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RContratoFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RCpfFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RDataNascimentoFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RDataVencFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RFilialFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RIdRegistroFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RLogradouroFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RNomeFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RNumEndFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RProvedor;
    private br.com.martinello.componentesbasicos.Rotulo RRGFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RSituacaoFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RStatusFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RUFFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo RValorFiltroAlterar;
    private br.com.martinello.componentesbasicos.Botao bCancelar;
    private br.com.martinello.componentesbasicos.Botao bFiltroAjuda;
    private br.com.martinello.componentesbasicos.Botao bFiltroAlterar;
    private br.com.martinello.componentesbasicos.Botao bFiltroCancelar;
    private br.com.martinello.componentesbasicos.Botao bFiltroGerarExcel;
    private br.com.martinello.componentesbasicos.Botao bFiltroPesquisar;
    private br.com.martinello.componentesbasicos.Botao bSalvar;
    private br.com.martinello.componentesbasicos.consulta.CampoCpfCnpjConsulta cccCpfCnpj;
    private br.com.martinello.componentesbasicos.CampoData cdDataEncontrado;
    private br.com.martinello.componentesbasicos.CampoData cdDataVencimentoFim;
    private br.com.martinello.componentesbasicos.CampoData cdDataVencimentoInicio;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsFiltroFilial;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsFiltroRegistroEncontrado;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsFiltroStatus;
    private br.com.martinello.componentesbasicos.CampoString csContratoDigitadoFiltroAlterar;
    private br.com.martinello.componentesbasicos.CampoString csContratoRelacionadoFiltroAlterar;
    private br.com.martinello.componentesbasicos.CampoString csFiltroContratoReal;
    private br.com.martinello.componentesbasicos.consulta.CampoStringConsulta cscFiltroNome;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox jcbContratoDigitado;
    private javax.swing.JCheckBox jcbContratoReal;
    private br.com.martinello.componentesbasicos.paineis.JPStatus jpsRelacionados;
    private javax.swing.JScrollPane jspRegistros;
    private br.com.martinello.componentesbasicos.paineis.PainelAba paRelacionados;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppAlterarRelacionado;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppFiltroRegistros;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppRegistros;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppRegistrosImportados;
    private br.com.martinello.componentesbasicos.Rotulo rBairroFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rCepFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rCidadeFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rClienteFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rContratoDigitadoFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rContratoFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rContratoRelacionadoFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rCpfFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rDataNascimentoFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rEnderecoFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rFilialFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroContratoReal;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroCpf;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroDataEncontrado;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroFilial;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroNome;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroRegistroEncontrado;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroStatus;
    private br.com.martinello.componentesbasicos.Rotulo rFiltroVencimento;
    private br.com.martinello.componentesbasicos.Rotulo rIdRegistroFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rInformacoes;
    private br.com.martinello.componentesbasicos.Rotulo rLogradouroFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rNomeFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rNumEndFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rParcelas;
    private br.com.martinello.componentesbasicos.Rotulo rProvedor;
    private br.com.martinello.componentesbasicos.Rotulo rRGFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rSituacaoFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rStatusFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rUFFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rValorFiltroAlterar;
    private br.com.martinello.componentesbasicos.Rotulo rVencimentoFiltroAlterar;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpRegistrosImportados;
    // End of variables declaration//GEN-END:variables
private void buscarImpcdl() {
        final TelaProcessamento telaProcessamento = new TelaProcessamento("Realizando consulta...");

        new Thread() {
            @Override
            public void run() {
                try {
                    ImpcdlModel impcdlModel = new ImpcdlModel();
                    impcdlControl = new ImpcdlController();
                    LImpcdl = new ArrayList<>();
                    if (!clsFiltroFilial.getSelectedItem().toString().equals("TODAS")) {
                        FilialController filialController = new FilialController();
                        FilialModel filialModel = new FilialModel();
                        String filial = clsFiltroFilial.getSelectedItem().toString();
                        try {
                            filialModel = filialController.listarFilialExtracao(filial);
                        } catch (ErroSistemaException ex) {
                            jpsRelacionados.setStatus(ex.getLocalizedMessage(), jpsRelacionados.ERRO, ex);
                        }
                        impcdlModel.setImpcdlFilial(filialModel.getFilialSgl());
                    }
                    if (clsFiltroRegistroEncontrado.getString().equalsIgnoreCase("Não")) {
                        impcdlModel.setEncontrado("N");
                    } else if (clsFiltroRegistroEncontrado.getString().equalsIgnoreCase("Sim")) {
                        impcdlModel.setEncontrado("S");
                    }
                    if (clsFiltroStatus.getString().equalsIgnoreCase("Importado")) {
                        impcdlModel.setStatus("I");
                    }
                    if (clsFiltroStatus.getString().equalsIgnoreCase("Aguardando")) {
                        impcdlModel.setStatus("A");
                    }
                    if (clsFiltroStatus.getString().equalsIgnoreCase("Prescrito")) {
                        impcdlModel.setStatus("P");
                    }
                    if (clsFiltroStatus.getString().equalsIgnoreCase("Baixado")) {
                        impcdlModel.setStatus("B");
                    }
                    if (csFiltroContratoReal.getString().trim().length() > 1) {
                        impcdlModel.setImpcdlContratoReal(csFiltroContratoReal.getString());
                    }
                    if (cccCpfCnpj.getFiltroOld() != null) {
                        impcdlModel.setImpcdlCpf(cccCpfCnpj.getFiltroOld().replaceAll("[^0-9]", ""));
                    }
                    if (cscFiltroNome.getFiltroOld() != null) {
                        impcdlModel.setImpcdlConsumidor(cscFiltroNome.getFiltroOld().toString().toUpperCase());
                    }
                    if (cdDataVencimentoInicio.getDate() != null) {
                        if (cdDataVencimentoFim.getDate() != null) {
                            impcdlModel.setImpcdlDataVencimento(Utilitarios.converteData(cdDataVencimentoInicio.getDate()));
                        } else {
                            jpsRelacionados.setStatus("O campo data envio precisa ser preenchido nos dois campos, por favor preencha o campo ao lado direito!", JPStatus.ALERTA, 20);

                        }

                    }
                    if (cdDataVencimentoFim.getDate() != null) {
                        if (cdDataVencimentoInicio.getDate() != null) {
                            impcdlModel.setImpcdlDataVencimentoFinal(Utilitarios.converteData(cdDataVencimentoFim.getDate()));
                        } else {
                            jpsRelacionados.setStatus("O campo data envio precisa ser preenchido nos dois campos, por favor preencha o campo ao lado esquerdo!", JPStatus.ALERTA, 20);

                        }

                    }
                    if (cdDataEncontrado.getDate() != null) {
                        impcdlModel.setDataEncontrado(cdDataEncontrado.getDate());
                    }

                    LImpcdl = impcdlControl.buscaImpcdl(impcdlModel);
                    otmImpcdl.setData(LImpcdl);
                    otmImpcdl.fireTableDataChanged();

                    jpsRelacionados.setStatus("Pesquisa realizada com sucesso.", jpsRelacionados.NORMAL);

                    if (tpRegistrosImportados.getRowCount() > 0) {
                        tpRegistrosImportados.packAll();
                        tpRegistrosImportados.addRowSelectionInterval(tpRegistrosImportados.convertRowIndexToView(0), tpRegistrosImportados.convertRowIndexToView(0));
                        tpRegistrosImportados.grabFocus();
                    }
                } catch (ErroSistemaException ex) {
                    ex.printStackTrace();
                    jpsRelacionados.setStatus(ex.getMessage(), jpsRelacionados.ERRO, ex);
                }
                SwingUtilities.invokeLater(() -> {
                    telaProcessamento.dispose();
                });
            }
        }.start();
        telaProcessamento.setVisible(true);
        telaProcessamento.requestFocusInWindow();
    }

    private void carregarFiliais() {
        for (FilialModel filial : TelaDadosGerais.lfiliaisModel) {
            clsFiltroFilial.addItem(filial);
        }

    }

    private void alterarRegistro() {
        int linha = tpRegistrosImportados.getSelectedRow();
        ImpcdlModel registro = new ImpcdlModel();

        if (linha < 0) {
            jpsRelacionados.setStatus("Nenhuma linha selecionada, por favor selecione uma linha", JPStatus.ALERTA);
        } else {

            RNomeFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getImpcdlConsumidor());
            RCpfFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getImpcdlCpf());
            RRGFiltroAlterar.setText("");
            Date dataNascimento = otmImpcdl.getValue(linha).getImpcdlDataNascimento();
            RDataNascimentoFiltroAlterar.setText(Utilitarios.converteDataString(dataNascimento, "dd/MM/yyyy"));
            RLogradouroFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getLogradouro());
            RBairroFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getImpcdlBairro());
            RCidadeFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getImpcdlCidade());
            RCepFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getImpcdlCep());
            RUFFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getImpcdlUf());
            RFilialFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getImpcdlFilial());
            RContratoFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getImpcdlContratoReal());
            RClienteFiltroAlterar.setText("");
            RSituacaoFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getStatus());
            RDataVencFiltroAlterar.setText(Utilitarios.converteDataString(otmImpcdl.getValue(linha).getImpcdlDataVencimento(), "dd/MM/yyyy"));
            RValorFiltroAlterar.setText(Utilitarios.doubleToString(otmImpcdl.getValue(linha).getImpcdlValor()));
            csContratoDigitadoFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getImpcdlContratoDigitado());
            csContratoRelacionadoFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getImpcdlContratoReal());
            csContratoDigitadoFiltroAlterar.setEnabled(false);
            csContratoRelacionadoFiltroAlterar.setEnabled(false);
            RStatusFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getStatus());
            RIdRegistroFiltroAlterar.setText((String) otmImpcdl.getValue(linha).getImpcdlId());
            RProvedor.setText((String) otmImpcdl.getValue(linha).getProvedor());
            paRelacionados.setSelectedComponent(ppAlterarRelacionado);
            paRelacionados.setEnabledAt(1, true);

        }
    }

    private void limpar() {
        clsFiltroFilial.setSelectedIndex(0);
        cscFiltroNome.setaValorFiltro("");
        cccCpfCnpj.setaValorFiltro("");
        csFiltroContratoReal.setText("");
        clsFiltroStatus.setSelectedIndex(4);
        clsFiltroRegistroEncontrado.setSelectedIndex(2);
        cdDataVencimentoInicio.setDate(null);
        cdDataVencimentoFim.setDate(null);
        cdDataEncontrado.setDate(null);
    }

    private void limparAlterar() {
        RNomeFiltroAlterar.setText("");
        RCpfFiltroAlterar.setText("");
        RRGFiltroAlterar.setText("");
        RDataNascimentoFiltroAlterar.setText("");
        RLogradouroFiltroAlterar.setText("");
        RBairroFiltroAlterar.setText("");
        RCidadeFiltroAlterar.setText("");
        RCepFiltroAlterar.setText("");
        RUFFiltroAlterar.setText("");
        RFilialFiltroAlterar.setText("");
        RContratoFiltroAlterar.setText("");
        RClienteFiltroAlterar.setText("");
        RSituacaoFiltroAlterar.setText("");
        RDataVencFiltroAlterar.setText("");
        RValorFiltroAlterar.setText("");
        csContratoDigitadoFiltroAlterar.setText("");
        csContratoRelacionadoFiltroAlterar.setText("");
        paRelacionados.setSelectedComponent(ppRegistrosImportados);
        paRelacionados.setEnabledAt(1, false);

    }

    private void alterarRelacionado() {
        ImpcdlModel impcdl = new ImpcdlModel();
        impcdlControl = new ImpcdlController();
        impcdl.setImpcdlContratoDigitado(csContratoDigitadoFiltroAlterar.getString());
        impcdl.setImpcdlContratoReal(csContratoRelacionadoFiltroAlterar.getString());
        impcdl.setImpcdlId(RIdRegistroFiltroAlterar.getText());
        try {
            impcdlControl.alterarRelacionado(impcdl);
            JOptionPane.showMessageDialog(null, "Registro alterado com sucesso!", "Informação", JOptionPane.DEFAULT_OPTION);
        } catch (ErroSistemaException ex) {
            ex.printStackTrace();
            jpsRelacionados.setStatus(ex.getMessage(), jpsRelacionados.ERRO, ex);
        }

    }
}
