/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.sistema.view;

import br.com.martinello.bd.matriz.control.ParcelaController;
import br.com.martinello.bd.matriz.model.domain.ExtracaoTableModel;
import br.com.martinello.componentesbasicos.view.TelaPadrao;
import br.com.martinello.util.excessoes.ErroSistemaException;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luiz.almeida
 */
public class TelaExtornoContasReceber extends TelaPadrao {

    private static ExtracaoTableModel extracao;

    /**
     * Creates new form TelaExtornoContasReceber
     */
    public TelaExtornoContasReceber(ExtracaoTableModel extracaoModel) {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        carregarDados(extracaoModel);
        extracao = new ExtracaoTableModel();
        extracao = extracaoModel;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        csCodFil = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        rNome = new br.com.martinello.componentesbasicos.Rotulo();
        rCpf = new br.com.martinello.componentesbasicos.Rotulo();
        rCodigoCliente = new br.com.martinello.componentesbasicos.Rotulo();
        rFilial = new br.com.martinello.componentesbasicos.Rotulo();
        rCidade = new br.com.martinello.componentesbasicos.Rotulo();
        rCep = new br.com.martinello.componentesbasicos.Rotulo();
        rContrato = new br.com.martinello.componentesbasicos.Rotulo();
        rValor = new br.com.martinello.componentesbasicos.Rotulo();
        rDataPagamento = new br.com.martinello.componentesbasicos.Rotulo();
        rSituacaoPago = new br.com.martinello.componentesbasicos.Rotulo();
        rDataLancamento = new br.com.martinello.componentesbasicos.Rotulo();
        rDataVencimento = new br.com.martinello.componentesbasicos.Rotulo();
        rDataExtracao = new br.com.martinello.componentesbasicos.Rotulo();
        rDataNegativada = new br.com.martinello.componentesbasicos.Rotulo();
        rDataBaixa = new br.com.martinello.componentesbasicos.Rotulo();
        csNome = new br.com.martinello.componentesbasicos.CampoString();
        csCpf = new br.com.martinello.componentesbasicos.CampoString();
        csCodigoCliente = new br.com.martinello.componentesbasicos.CampoString();
        csFilial = new br.com.martinello.componentesbasicos.CampoString();
        csCidade = new br.com.martinello.componentesbasicos.CampoString();
        ccpCep = new br.com.martinello.componentesbasicos.CampoCEP();
        csContrato = new br.com.martinello.componentesbasicos.CampoString();
        csvalor = new br.com.martinello.componentesbasicos.CampoString();
        csSituacaoPagamento = new br.com.martinello.componentesbasicos.CampoString();
        cdDataNegativada = new br.com.martinello.componentesbasicos.CampoData();
        cdDataBaixa = new br.com.martinello.componentesbasicos.CampoData();
        jcbDataBaixa = new javax.swing.JCheckBox();
        bSalvar = new br.com.martinello.componentesbasicos.Botao();
        bCancelar = new br.com.martinello.componentesbasicos.Botao();
        cdDataPagamento = new br.com.martinello.componentesbasicos.CampoData();
        cdDataLancamento = new br.com.martinello.componentesbasicos.CampoData();
        cdDataVencimento = new br.com.martinello.componentesbasicos.CampoData();
        cdDataExtracao = new br.com.martinello.componentesbasicos.CampoData();
        jcbDataNegativacao = new javax.swing.JCheckBox();
        rCodFil = new br.com.martinello.componentesbasicos.Rotulo();
        csFilial1 = new br.com.martinello.componentesbasicos.CampoString();
        jpsExtorno = new br.com.martinello.componentesbasicos.paineis.JPStatus();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gravar Data Contas Receber");
        setPreferredSize(new java.awt.Dimension(1366, 768));

        csCodFil.setToolTipText("A data de baixa p/ extorno precisa ser = '31/12/1900'");
        csCodFil.setPreferredSize(new java.awt.Dimension(1024, 637));

        rNome.setText("Nome:");

        rCpf.setText("Cpf:");

        rCodigoCliente.setText("Código Cliente:");

        rFilial.setText("Filial:");

        rCidade.setText("Cidade:");

        rCep.setText("Cep:");

        rContrato.setText("Contrato:");

        rValor.setText("Valor:");

        rDataPagamento.setText("Data Pagamento:");

        rSituacaoPago.setText("Pago:");

        rDataLancamento.setText("Data Lançamento:");

        rDataVencimento.setText("Data Vencimento:");

        rDataExtracao.setText("Data Extração:");

        rDataNegativada.setText("Data Negativada:");

        rDataBaixa.setText("Data Baixa:");

        csNome.setEnabled(false);

        csCpf.setEnabled(false);

        csCodigoCliente.setEnabled(false);

        csFilial.setEnabled(false);

        csCidade.setEnabled(false);

        ccpCep.setEnabled(false);

        csContrato.setEnabled(false);

        csvalor.setEnabled(false);

        csSituacaoPagamento.setEnabled(false);

        cdDataNegativada.setEnabled(false);

        cdDataBaixa.setToolTipText("A data da baixa para extorno precisa ser = '31/12/1900'");
        cdDataBaixa.setEnabled(false);

        jcbDataBaixa.setText("Alterar");
        jcbDataBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDataBaixaActionPerformed(evt);
            }
        });

        bSalvar.setText("Salvar/Alterar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        cdDataPagamento.setEnabled(false);

        cdDataLancamento.setEnabled(false);

        cdDataVencimento.setEnabled(false);

        cdDataExtracao.setEnabled(false);

        jcbDataNegativacao.setText("Alterar");
        jcbDataNegativacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDataNegativacaoActionPerformed(evt);
            }
        });

        rCodFil.setText("CodFil:");

        csFilial1.setEnabled(false);

        javax.swing.GroupLayout csCodFilLayout = new javax.swing.GroupLayout(csCodFil);
        csCodFil.setLayout(csCodFilLayout);
        csCodFilLayout.setHorizontalGroup(
            csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csCodFilLayout.createSequentialGroup()
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(csCodFilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(csCodFilLayout.createSequentialGroup()
                                .addComponent(rNome, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(csNome, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(csCodFilLayout.createSequentialGroup()
                                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(csCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(csFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(csCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(csCodFilLayout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(csCodFilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(csCodFilLayout.createSequentialGroup()
                                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rDataBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rValor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rSituacaoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rDataExtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rDataNegativada, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rDataLancamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rDataVencimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(csContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(csvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(csSituacaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(csCodFilLayout.createSequentialGroup()
                                        .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cdDataBaixa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cdDataNegativada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbDataBaixa)
                                            .addComponent(jcbDataNegativacao)))
                                    .addComponent(cdDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdDataExtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(csCodFilLayout.createSequentialGroup()
                                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rCep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(csCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ccpCep, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(csCodFilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rCodFil, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(csFilial1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(693, Short.MAX_VALUE))
        );
        csCodFilLayout.setVerticalGroup(
            csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csCodFilLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rCodFil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csFilial1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(csCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCep, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccpCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rValor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSituacaoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csSituacaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataExtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdDataExtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDataNegativada, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdDataNegativada, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbDataNegativacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rDataBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cdDataBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbDataBaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addGroup(csCodFilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(csCodFil, java.awt.BorderLayout.CENTER);
        getContentPane().add(jpsExtorno, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbDataBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDataBaixaActionPerformed
        if (jcbDataBaixa.isSelected()) {
            cdDataBaixa.setEnabled(true);
        } else {
            cdDataBaixa.setEnabled(false);
        }
    }//GEN-LAST:event_jcbDataBaixaActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        extornarContasReceber(extracao);
        JOptionPane.showMessageDialog(null, "Registro alterado com sucesso!", "Informação", JOptionPane.DEFAULT_OPTION);
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }        
          this.dispose();
                 
    }//GEN-LAST:event_bSalvarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void jcbDataNegativacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDataNegativacaoActionPerformed
      if (jcbDataNegativacao.isSelected()) {
            cdDataNegativada.setEnabled(true);
        } else {
            cdDataNegativada.setEnabled(false);
        }
    }//GEN-LAST:event_jcbDataNegativacaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.componentesbasicos.Botao bCancelar;
    private br.com.martinello.componentesbasicos.Botao bSalvar;
    private br.com.martinello.componentesbasicos.CampoCEP ccpCep;
    private br.com.martinello.componentesbasicos.CampoData cdDataBaixa;
    private br.com.martinello.componentesbasicos.CampoData cdDataExtracao;
    private br.com.martinello.componentesbasicos.CampoData cdDataLancamento;
    private br.com.martinello.componentesbasicos.CampoData cdDataNegativada;
    private br.com.martinello.componentesbasicos.CampoData cdDataPagamento;
    private br.com.martinello.componentesbasicos.CampoData cdDataVencimento;
    private br.com.martinello.componentesbasicos.CampoString csCidade;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao csCodFil;
    private br.com.martinello.componentesbasicos.CampoString csCodigoCliente;
    private br.com.martinello.componentesbasicos.CampoString csContrato;
    private br.com.martinello.componentesbasicos.CampoString csCpf;
    private br.com.martinello.componentesbasicos.CampoString csFilial;
    private br.com.martinello.componentesbasicos.CampoString csFilial1;
    private br.com.martinello.componentesbasicos.CampoString csNome;
    private br.com.martinello.componentesbasicos.CampoString csSituacaoPagamento;
    private br.com.martinello.componentesbasicos.CampoString csvalor;
    private javax.swing.JCheckBox jcbDataBaixa;
    private javax.swing.JCheckBox jcbDataNegativacao;
    private br.com.martinello.componentesbasicos.paineis.JPStatus jpsExtorno;
    private br.com.martinello.componentesbasicos.Rotulo rCep;
    private br.com.martinello.componentesbasicos.Rotulo rCidade;
    private br.com.martinello.componentesbasicos.Rotulo rCodFil;
    private br.com.martinello.componentesbasicos.Rotulo rCodigoCliente;
    private br.com.martinello.componentesbasicos.Rotulo rContrato;
    private br.com.martinello.componentesbasicos.Rotulo rCpf;
    private br.com.martinello.componentesbasicos.Rotulo rDataBaixa;
    private br.com.martinello.componentesbasicos.Rotulo rDataExtracao;
    private br.com.martinello.componentesbasicos.Rotulo rDataLancamento;
    private br.com.martinello.componentesbasicos.Rotulo rDataNegativada;
    private br.com.martinello.componentesbasicos.Rotulo rDataPagamento;
    private br.com.martinello.componentesbasicos.Rotulo rDataVencimento;
    private br.com.martinello.componentesbasicos.Rotulo rFilial;
    private br.com.martinello.componentesbasicos.Rotulo rNome;
    private br.com.martinello.componentesbasicos.Rotulo rSituacaoPago;
    private br.com.martinello.componentesbasicos.Rotulo rValor;
    // End of variables declaration//GEN-END:variables
private void carregarDados(ExtracaoTableModel extracaoModel) {
        csNome.setText(extracaoModel.getNome());
        csCpf.setText(extracaoModel.getCpfCnpj());
        csCidade.setText(extracaoModel.getCidade());
        csFilial.setText(extracaoModel.getIdFilial());
        ccpCep.setText(extracaoModel.getCep());
        csvalor.setText("" + extracaoModel.getValor());
        csSituacaoPagamento.setText(extracaoModel.getPago());
        csContrato.setText(extracaoModel.getNumeroDoc());
        csCodigoCliente.setText(extracaoModel.getCodigoCliente());
        cdDataExtracao.setDate(extracaoModel.getDataExtracao());
        cdDataLancamento.setDate(extracaoModel.getDataLancamento());
        cdDataPagamento.setDate(extracaoModel.getDataPagamento());
        cdDataVencimento.setDate(extracaoModel.getDataVencimento());
        cdDataBaixa.setDate(extracaoModel.getDataBaixa());
        cdDataNegativada.setDate(extracaoModel.getDataNegativada());
    }

    private void extornarContasReceber(ExtracaoTableModel extracaoModel) {
        ParcelaController parcela = new ParcelaController();
        extracaoModel.setDataBaixa(cdDataBaixa.getDate());
        extracaoModel.setDataNegativada(cdDataNegativada.getDate());
        try {
            if(extracaoModel.getOrigemBd().equalsIgnoreCase("SGL")){
            parcela.ExtornoContasReceber(extracaoModel);
            }
            if(extracaoModel.getOrigemBd().equalsIgnoreCase("NOVO_SGL")){
               parcela.ExtornoE301TCR(extracaoModel, ""); 
            }
            
        } catch (ErroSistemaException ex) {
            ex.printStackTrace();
            jpsExtorno.setStatus(ex.getMessage(), jpsExtorno.ERRO, ex);
        }
    }
}
