/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.sistema.view;

import br.com.martinello.bd.matriz.control.UsuarioController;
import br.com.martinello.bd.matriz.model.domain.UsuarioModel;
import br.com.martinello.componentesbasicos.paineis.JPStatus;
import br.com.martinello.componentesbasicos.view.TelaPadrao;
import br.com.martinello.util.excessoes.ErroSistemaException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.towel.swing.table.ObjectTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author luiz.almeida
 */
public class TelaCadastroUsuario extends TelaPadrao {

    private UsuarioController usuarioController;
    private int resultadoInsert;
    private UsuarioModel usuarioModel;
    private char previousEchoChar = '\u2022';
    public List<UsuarioModel> lUsuarioModel;

    private final ObjectTableModel<UsuarioModel> otmUsuario = new ObjectTableModel<>(UsuarioModel.class, "idUsuario,nome,login,senha,status,nivelLiberacao,dataHoraCadastro,dataHoraAtualizacao");

    /**
     * Creates new form TelaUsuario
     */
    public TelaCadastroUsuario() {
        initComponents();
        buscarUsuarios();
        paUsuario.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paUsuario = new br.com.martinello.componentesbasicos.paineis.PainelAba();
        ppCadastroUsuario = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        ppFiltroUsuario = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        clsStatusUser = new br.com.martinello.componentesbasicos.CampoListaSimples();
        clsPerfilUser = new br.com.martinello.componentesbasicos.CampoListaSimples();
        rPerfilUser = new br.com.martinello.componentesbasicos.Rotulo();
        rStatusUser = new br.com.martinello.componentesbasicos.Rotulo();
        rSenha = new br.com.martinello.componentesbasicos.Rotulo();
        csSenha = new br.com.martinello.componentesbasicos.CampoSenha();
        jcbVizualizarSenha = new javax.swing.JCheckBox();
        csNomeLogin = new br.com.martinello.componentesbasicos.CampoString();
        csNome = new br.com.martinello.componentesbasicos.CampoString();
        rNomeLogin = new br.com.martinello.componentesbasicos.Rotulo();
        rNome = new br.com.martinello.componentesbasicos.Rotulo();
        bCancelar = new br.com.martinello.componentesbasicos.Botao();
        bSalvar = new br.com.martinello.componentesbasicos.Botao();
        bAtualizar = new br.com.martinello.componentesbasicos.Botao();
        botao1 = new br.com.martinello.componentesbasicos.Botao();
        botao2 = new br.com.martinello.componentesbasicos.Botao();
        ppTabelaUsuario = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        jspUsuario = new javax.swing.JScrollPane();
        tpUsuarios = new br.com.martinello.componentesbasicos.TabelaPadrao();
        ppAlterar = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        rNOmeAlt = new br.com.martinello.componentesbasicos.Rotulo();
        csNomeAlt = new br.com.martinello.componentesbasicos.CampoString();
        csNomeLoginAlt = new br.com.martinello.componentesbasicos.CampoString();
        jcbVerSenhaAlt = new javax.swing.JCheckBox();
        csSenhaAlt = new br.com.martinello.componentesbasicos.CampoSenha();
        rSenhaAlt = new br.com.martinello.componentesbasicos.Rotulo();
        rNomeLoginAlt = new br.com.martinello.componentesbasicos.Rotulo();
        rPerfilUserAlt = new br.com.martinello.componentesbasicos.Rotulo();
        clsPerfilUserAlt = new br.com.martinello.componentesbasicos.CampoListaSimples();
        clsStatususerAlt = new br.com.martinello.componentesbasicos.CampoListaSimples();
        rStatusUserAlt = new br.com.martinello.componentesbasicos.Rotulo();
        rDataAlteracaoAlt = new br.com.martinello.componentesbasicos.Rotulo();
        cdDatasAlt = new br.com.martinello.componentesbasicos.CampoData();
        bCancelarAlt = new br.com.martinello.componentesbasicos.Botao();
        bSalvarAlt = new br.com.martinello.componentesbasicos.Botao();
        rotulo1 = new br.com.martinello.componentesbasicos.Rotulo();
        csIdUsuarioAlt = new br.com.martinello.componentesbasicos.CampoString();
        jpsUsuario = new br.com.martinello.componentesbasicos.paineis.JPStatus();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Usuário");
        setPreferredSize(new java.awt.Dimension(1366, 768));

        ppCadastroUsuario.setLayout(new java.awt.BorderLayout());

        ppFiltroUsuario.setPreferredSize(new java.awt.Dimension(1155, 180));

        clsStatusUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "INATIVO" }));
        clsStatusUser.setDescricaoRotulo("");

        clsPerfilUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NAO" }));
        clsPerfilUser.setDescricaoRotulo("");

        rPerfilUser.setText("Perfil Admin:");

        rStatusUser.setText("Status:");

        rSenha.setText("Senha:");

        csSenha.setDescricaoRotulo("");

        jcbVizualizarSenha.setText("Vizualizar");
        jcbVizualizarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVizualizarSenhaActionPerformed(evt);
            }
        });

        csNomeLogin.setEditable(false);

        csNome.setObrigatorio(true);
        csNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                csNomeFocusLost(evt);
            }
        });
        csNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csNomeActionPerformed(evt);
            }
        });

        rNomeLogin.setText("Nome login:");

        rNome.setText("Nome Completo:");

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bAtualizar.setText("Pesquisar");
        bAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarActionPerformed(evt);
            }
        });

        botao1.setText("Extrair");

        botao2.setText("Ajuda");

        javax.swing.GroupLayout ppFiltroUsuarioLayout = new javax.swing.GroupLayout(ppFiltroUsuario);
        ppFiltroUsuario.setLayout(ppFiltroUsuarioLayout);
        ppFiltroUsuarioLayout.setHorizontalGroup(
            ppFiltroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFiltroUsuarioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ppFiltroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rPerfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rStatusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rNomeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppFiltroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(csNome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsPerfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ppFiltroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(csNomeLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ppFiltroUsuarioLayout.createSequentialGroup()
                            .addComponent(csSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcbVizualizarSenha)
                            .addGap(5, 5, 5)))
                    .addComponent(clsStatusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 709, Short.MAX_VALUE)
                .addGroup(ppFiltroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ppFiltroUsuarioLayout.setVerticalGroup(
            ppFiltroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFiltroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ppFiltroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppFiltroUsuarioLayout.createSequentialGroup()
                        .addGroup(ppFiltroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csNome, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(bAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppFiltroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rNomeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csNomeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppFiltroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbVizualizarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppFiltroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clsPerfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppFiltroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rStatusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clsStatusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ppFiltroUsuarioLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(rPerfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        ppCadastroUsuario.add(ppFiltroUsuario, java.awt.BorderLayout.NORTH);

        ppTabelaUsuario.setLayout(new java.awt.BorderLayout());

        tpUsuarios.setModel(otmUsuario);
        tpUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpUsuariosMouseClicked(evt);
            }
        });
        jspUsuario.setViewportView(tpUsuarios);

        ppTabelaUsuario.add(jspUsuario, java.awt.BorderLayout.CENTER);

        ppCadastroUsuario.add(ppTabelaUsuario, java.awt.BorderLayout.CENTER);

        paUsuario.addTab("Cadastro", ppCadastroUsuario);

        ppAlterar.setPreferredSize(new java.awt.Dimension(1241, 706));

        rNOmeAlt.setText("Nome Completo:");

        csNomeAlt.setObrigatorio(true);
        csNomeAlt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                csNomeAltFocusLost(evt);
            }
        });
        csNomeAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csNomeAltActionPerformed(evt);
            }
        });

        csNomeLoginAlt.setEditable(false);

        jcbVerSenhaAlt.setText("Vizualizar");
        jcbVerSenhaAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVerSenhaAltActionPerformed(evt);
            }
        });

        csSenhaAlt.setDescricaoRotulo("");

        rSenhaAlt.setText("Senha:");

        rNomeLoginAlt.setText("Nome login:");

        rPerfilUserAlt.setText("Perfil Admin:");

        clsPerfilUserAlt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NAO" }));
        clsPerfilUserAlt.setDescricaoRotulo("");

        clsStatususerAlt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "INATIVO" }));
        clsStatususerAlt.setDescricaoRotulo("");

        rStatusUserAlt.setText("Status:");

        rDataAlteracaoAlt.setText("Data Alteração:");

        cdDatasAlt.setEditable(false);
        cdDatasAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdDatasAltActionPerformed(evt);
            }
        });

        bCancelarAlt.setText("Cancelar");
        bCancelarAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarAltActionPerformed(evt);
            }
        });

        bSalvarAlt.setText("Salvar");
        bSalvarAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarAltActionPerformed(evt);
            }
        });

        rotulo1.setText("ID Usuário:");

        csIdUsuarioAlt.setEditable(false);

        javax.swing.GroupLayout ppAlterarLayout = new javax.swing.GroupLayout(ppAlterar);
        ppAlterar.setLayout(ppAlterarLayout);
        ppAlterarLayout.setHorizontalGroup(
            ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppAlterarLayout.createSequentialGroup()
                .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppAlterarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rDataAlteracaoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdDatasAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ppAlterarLayout.createSequentialGroup()
                        .addGap(511, 511, 511)
                        .addComponent(bCancelarAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSalvarAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ppAlterarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rotulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rPerfilUserAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rStatusUserAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rNomeLoginAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rNOmeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(csNomeLoginAlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ppAlterarLayout.createSequentialGroup()
                                    .addComponent(csSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jcbVerSenhaAlt)
                                    .addGap(5, 5, 5)))
                            .addComponent(clsPerfilUserAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clsStatususerAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csIdUsuarioAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(628, Short.MAX_VALUE))
        );
        ppAlterarLayout.setVerticalGroup(
            ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppAlterarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csIdUsuarioAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rNOmeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csNomeAlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rNomeLoginAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csNomeLoginAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbVerSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rPerfilUserAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsPerfilUserAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rStatusUserAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsStatususerAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cdDatasAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rDataAlteracaoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 454, Short.MAX_VALUE)
                .addGroup(ppAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelarAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSalvarAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        paUsuario.addTab("Alterar", ppAlterar);

        getContentPane().add(paUsuario, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jpsUsuario, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed

    }//GEN-LAST:event_bCancelarActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        usuarioController = new UsuarioController();
        usuarioModel = new UsuarioModel();
        if (csNome.getText().equals("")) {
            jpsUsuario.setStatus("O campo nome não pode ser vazio, por favor preencha o campo nome", JPStatus.ALERTA);
        }
        if (csSenha.getString().equals("")) {
            jpsUsuario.setStatus("O campo Senha não pode ser vazio, por favor preencha o campo Senha", JPStatus.ALERTA);
        } else {
            usuarioModel.setNome(csNome.getText().toUpperCase());
            usuarioModel.setLogin(csNomeLogin.getText().toLowerCase());
            usuarioModel.setSenha(csSenha.getString());
            if (clsPerfilUser.getSelectedItem().toString().equals("SIM")) {
                usuarioModel.setNivelLiberacao("ADMIN");
            } else {
                usuarioModel.setNivelLiberacao("NORMAL");
            }

            if (clsStatusUser.getSelectedItem().toString().equals("ATIVO")) {
                usuarioModel.setStatus("A");
            } else {
                usuarioModel.setStatus("I");

            }

            try {
                resultadoInsert = usuarioController.salvarAtualizar(usuarioModel);
                jpsUsuario.setStatus("Usuário cadastrado com sucesso", JPStatus.NORMAL);
                Limpar();
            } catch (ErroSistemaException ex) {
                jpsUsuario.setStatus("Erro ao Inserir usuário " + "Erro Sistema.: " + ex.getMessage(), JPStatus.ERRO);
                Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_bSalvarActionPerformed

    private void jcbVizualizarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVizualizarSenhaActionPerformed
        if (jcbVizualizarSenha.isSelected()) {
            previousEchoChar = csSenha.getEchoChar();
            csSenha.setEchoChar('\u0000');
        } else {
            csSenha.setEchoChar(previousEchoChar);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jcbVizualizarSenhaActionPerformed

    private void csNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_csNomeFocusLost
        if (csNome.getText().length() > 1) {
            String nome1 = csNome.getText().substring(0, csNome.getText().indexOf(" "));//até o primeiro espaço
            String sobrenome = csNome.getText().substring(csNome.getText().lastIndexOf(" ") + 1, csNome.getText().length());//depois do primeiro espaço
            csNomeLogin.setText(nome1.toLowerCase() + "." + sobrenome.toLowerCase());
        }

    }//GEN-LAST:event_csNomeFocusLost

    private void csNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csNomeActionPerformed

    private void csNomeAltFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_csNomeAltFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_csNomeAltFocusLost

    private void csNomeAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csNomeAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csNomeAltActionPerformed

    private void jcbVerSenhaAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVerSenhaAltActionPerformed
       if (jcbVerSenhaAlt.isSelected()) {
            previousEchoChar = csSenhaAlt.getEchoChar();
            csSenhaAlt.setEchoChar('\u0000');
        } else {
            csSenhaAlt.setEchoChar(previousEchoChar);
        }
    }//GEN-LAST:event_jcbVerSenhaAltActionPerformed

    private void bCancelarAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarAltActionPerformed
      LimparAlt();
    }//GEN-LAST:event_bCancelarAltActionPerformed

    private void bSalvarAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarAltActionPerformed
        usuarioController = new UsuarioController();
        usuarioModel = new UsuarioModel();
        if (csNomeAlt.getText().equals("")) {
            jpsUsuario.setStatus("O campo nome não pode ser vazio, por favor preencha o campo nome", JPStatus.ALERTA);
        }
        if (csSenhaAlt.getString().equals("")) {
            jpsUsuario.setStatus("O campo Senha não pode ser vazio, por favor preencha o campo Senha", JPStatus.ALERTA);
        } else {
            usuarioModel.setNome(csNomeAlt.getText().toUpperCase());
            usuarioModel.setLogin(csNomeLoginAlt.getText().toLowerCase());
            usuarioModel.setSenha(csSenhaAlt.getString());
            if (clsPerfilUserAlt.getSelectedItem().toString().equals("SIM")) {
                usuarioModel.setNivelLiberacao("ADMIN");
            } else {
                usuarioModel.setNivelLiberacao("NORMAL");
            }

            if (clsStatususerAlt.getSelectedItem().toString().equals("ATIVO")) {
                usuarioModel.setStatus("A");
            } else {
                usuarioModel.setStatus("I");

            }

            try {
                usuarioController.salvarAlteracao(usuarioModel);
            } catch (SQLException ex) {
                ex.printStackTrace();
                jpsUsuario.setStatus("Falha ao Salvar!", JPStatus.ERRO, ex);
            } catch (ErroSistemaException ex) {
                ex.printStackTrace();
                jpsUsuario.setStatus("Falha ao Salvar!", JPStatus.ERRO, ex);
            }
            jpsUsuario.setStatus("Usuário Alterado com sucesso", JPStatus.NORMAL);
            Limpar();
        }

    }//GEN-LAST:event_bSalvarAltActionPerformed

    private void cdDatasAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdDatasAltActionPerformed

    }//GEN-LAST:event_cdDatasAltActionPerformed

    private void bAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarActionPerformed
        buscarUsuarios();
    }//GEN-LAST:event_bAtualizarActionPerformed

    private void tpUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpUsuariosMouseClicked
        if (evt.getClickCount() == 2) {
            alterarUsuario();
            ppAlterar.setVisible(true);
        }
    }//GEN-LAST:event_tpUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.componentesbasicos.Botao bAtualizar;
    private br.com.martinello.componentesbasicos.Botao bCancelar;
    private br.com.martinello.componentesbasicos.Botao bCancelarAlt;
    private br.com.martinello.componentesbasicos.Botao bSalvar;
    private br.com.martinello.componentesbasicos.Botao bSalvarAlt;
    private br.com.martinello.componentesbasicos.Botao botao1;
    private br.com.martinello.componentesbasicos.Botao botao2;
    private br.com.martinello.componentesbasicos.CampoData cdDatasAlt;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsPerfilUser;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsPerfilUserAlt;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsStatusUser;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsStatususerAlt;
    private br.com.martinello.componentesbasicos.CampoString csIdUsuarioAlt;
    private br.com.martinello.componentesbasicos.CampoString csNome;
    private br.com.martinello.componentesbasicos.CampoString csNomeAlt;
    private br.com.martinello.componentesbasicos.CampoString csNomeLogin;
    private br.com.martinello.componentesbasicos.CampoString csNomeLoginAlt;
    private br.com.martinello.componentesbasicos.CampoSenha csSenha;
    private br.com.martinello.componentesbasicos.CampoSenha csSenhaAlt;
    private javax.swing.JCheckBox jcbVerSenhaAlt;
    private javax.swing.JCheckBox jcbVizualizarSenha;
    private br.com.martinello.componentesbasicos.paineis.JPStatus jpsUsuario;
    private javax.swing.JScrollPane jspUsuario;
    private br.com.martinello.componentesbasicos.paineis.PainelAba paUsuario;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppAlterar;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppCadastroUsuario;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppFiltroUsuario;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppTabelaUsuario;
    private br.com.martinello.componentesbasicos.Rotulo rDataAlteracaoAlt;
    private br.com.martinello.componentesbasicos.Rotulo rNOmeAlt;
    private br.com.martinello.componentesbasicos.Rotulo rNome;
    private br.com.martinello.componentesbasicos.Rotulo rNomeLogin;
    private br.com.martinello.componentesbasicos.Rotulo rNomeLoginAlt;
    private br.com.martinello.componentesbasicos.Rotulo rPerfilUser;
    private br.com.martinello.componentesbasicos.Rotulo rPerfilUserAlt;
    private br.com.martinello.componentesbasicos.Rotulo rSenha;
    private br.com.martinello.componentesbasicos.Rotulo rSenhaAlt;
    private br.com.martinello.componentesbasicos.Rotulo rStatusUser;
    private br.com.martinello.componentesbasicos.Rotulo rStatusUserAlt;
    private br.com.martinello.componentesbasicos.Rotulo rotulo1;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpUsuarios;
    // End of variables declaration//GEN-END:variables

    public boolean buscarUsuarios() {
        lUsuarioModel = new ArrayList();
        UsuarioController usuarios = new UsuarioController();
        try {
            lUsuarioModel = usuarios.listarUsuarios();
            otmUsuario.setData(lUsuarioModel);

            otmUsuario.fireTableDataChanged();
            jpsUsuario.setStatus("Pesquisa realizada com sucesso.", JPStatus.NORMAL);
            if (tpUsuarios.getRowCount() > 0) {
                tpUsuarios.packAll();
                tpUsuarios.addRowSelectionInterval(tpUsuarios.convertRowIndexToView(0), tpUsuarios.convertRowIndexToView(0));
                tpUsuarios.grabFocus();
            }
        } catch (ErroSistemaException ex) {
            Logger.getLogger(TelaDadosGerais.class.getName()).log(Level.SEVERE, null, ex);
        }

        return false;

    }

    private void Limpar() {
        csNome.setText("");
        csNomeLogin.setText("");
        csSenha.setString("");
    }
    private void LimparAlt() {
        csNomeAlt.setText("");
        csNomeLoginAlt.setText("");
        csSenhaAlt.setString("");
        ppAlterar.setVisible(false);
    }

    private void alterarUsuario() {
        usuarioModel = new UsuarioModel();
        usuarioController = new UsuarioController();
        int linha = tpUsuarios.getSelectedRow();
        long conta = 0;
        if (linha < 0) {
            jpsUsuario.setStatus("Selecione uma Filial na Tabela, antes de clicar em alterar", JPStatus.ALERTA);
        } else {

            conta = (long) tpUsuarios.getValueAt(linha, 0);
            try {
                usuarioController.buscarConta(usuarioModel, conta);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ErroSistemaException ex) {
                Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

            csIdUsuarioAlt.setText("" + usuarioModel.getIdUsuario());
            csNomeAlt.setText(usuarioModel.getNome());
            csNomeLoginAlt.setText(usuarioModel.getLogin());
            csSenhaAlt.setText(usuarioModel.getSenha());
            cdDatasAlt.setDate(usuarioModel.getDataHoraAtualizacao());
            paUsuario.setSelectedComponent(ppAlterar);

        }
    }
}
