/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.sistema.view.painel;

import br.com.martinello.bd.matriz.model.domain.ConsultaClienteControl;
import br.com.martinello.componentesbasicos.paineis.JPStatus;
import br.com.martinello.componentesbasicos.paineis.Painel;
import br.com.martinello.consulta.Domain.ConsultaClienteModel;
import br.com.martinello.consulta.Domain.ConsultaSpcBvsModel;
import br.com.martinello.consulta.Domain.DadosComerciaisModel;
import br.com.martinello.consulta.Domain.EnderecoModel;
import br.com.martinello.consulta.Domain.HistoricoCliente;
import br.com.martinello.consulta.Domain.ObservacaoModel;
import br.com.martinello.consulta.Domain.ReferenciasModel;
import br.com.martinello.sistema.view.TelaContasReceber;
import static br.com.martinello.sistema.view.TelaContasReceber.consultaCliente;
import br.com.martinello.util.excessoes.ErroSistemaException;
import com.towel.swing.table.ObjectTableModel;

/**
 *
 * @author luiz.almeida
 */
public class PainelCliente extends Painel {

    /**
     * Creates new form PainelCliente
     */
    public int tQuitacao,
            /**
             * Creates new form PainelCliente
             */
            tParcial,
            /**
             * Creates new form PainelCliente
             */
            tRenegociacao,
            /**
             * Creates new form PainelCliente
             */
            tDevolucao,
            /**
             * Creates new form PainelCliente
             */
            tTransf,
            /**
             * Creates new form PainelCliente
             */
            tPerdida;
    public double valorTraz, valorCalc, valorAberto, valorParcela, valorOriginal, valorVencer;
    private boolean resultado;
    public ConsultaClienteControl consultaClienteControl;
    
    private final ObjectTableModel<EnderecoModel> otmClienteEndereco = new ObjectTableModel<>(EnderecoModel.class, "tipoDocumento,documento,descricao,endLogradouro,endNumero,endComplemento,"
            + "endBairro,cidade,ufEstado,cep,codigoIbge");
    private final ObjectTableModel<ReferenciasModel> otmReferencias = new ObjectTableModel<>(ReferenciasModel.class, "tipo,dataConsulta,referencia,resultado,dataCadastro,dataUltCompra,"
            + "diasMedios,valorUltCompra,valorAberto,valorQuitado,valorEmAberto,tipoPagamento");
    private final ObjectTableModel<ConsultaSpcBvsModel> otmConsulta = new ObjectTableModel<>(ConsultaSpcBvsModel.class, "tipo,data,resultado,usuario");
    private final ObjectTableModel<DadosComerciaisModel> otmDadosComerciais = new ObjectTableModel<>(DadosComerciaisModel.class, "empresa,ocupacao,cargo,dataAdmicao,telefone,contato,dataGeracao,"
            + "usuarioGeracao,DataAlteracao,usuarioAlteracao");
    private final ObjectTableModel<HistoricoCliente> otmHistorico = new ObjectTableModel<>(HistoricoCliente.class, "tipo,data,usuario");
    private final ObjectTableModel<ObservacaoModel> otmObservacao = new ObjectTableModel<>(ObservacaoModel.class, "clienteEndereco,tipo,descricao,dataGeracao,usuarioGer");
    
    public PainelCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        ppClienteAba = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        paCliente = new br.com.martinello.componentesbasicos.paineis.PainelAba();
        ppCliente = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        rotulo2 = new br.com.martinello.componentesbasicos.Rotulo();
        rotulo3 = new br.com.martinello.componentesbasicos.Rotulo();
        rotulo4 = new br.com.martinello.componentesbasicos.Rotulo();
        csRazaoSocial = new br.com.martinello.componentesbasicos.CampoString();
        rotulo6 = new br.com.martinello.componentesbasicos.Rotulo();
        csNomeFantazia = new br.com.martinello.componentesbasicos.CampoString();
        rotulo7 = new br.com.martinello.componentesbasicos.Rotulo();
        csEmail = new br.com.martinello.componentesbasicos.CampoString();
        rotulo8 = new br.com.martinello.componentesbasicos.Rotulo();
        rotulo9 = new br.com.martinello.componentesbasicos.Rotulo();
        rotulo10 = new br.com.martinello.componentesbasicos.Rotulo();
        csContato = new br.com.martinello.componentesbasicos.CampoString();
        rotulo11 = new br.com.martinello.componentesbasicos.Rotulo();
        rotulo14 = new br.com.martinello.componentesbasicos.Rotulo();
        clsTipoPessoa = new br.com.martinello.componentesbasicos.CampoListaSimples();
        clsNegativado = new br.com.martinello.componentesbasicos.CampoListaSimples();
        cccCpfCnpj = new br.com.martinello.componentesbasicos.CampoCpfCnpj();
        ctTelefone = new br.com.martinello.componentesbasicos.CampoTelefone();
        ctCelular = new br.com.martinello.componentesbasicos.CampoTelefone();
        ciCodCli = new br.com.martinello.componentesbasicos.CampoInteiro();
        rotulo1 = new br.com.martinello.componentesbasicos.Rotulo();
        clsSitCli = new br.com.martinello.componentesbasicos.CampoListaSimples();
        ppEndereco = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        pTableEndereco = new br.com.martinello.componentesbasicos.paineis.Painel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpEndereco = new br.com.martinello.componentesbasicos.TabelaPadrao();
        ppDadosCompl = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        pDadosCompl = new br.com.martinello.componentesbasicos.paineis.Painel();
        PDadosConjugue = new br.com.martinello.componentesbasicos.paineis.Painel();
        rCpf = new br.com.martinello.componentesbasicos.Rotulo();
        rNaturalidaConj = new br.com.martinello.componentesbasicos.Rotulo();
        rDocumento = new br.com.martinello.componentesbasicos.Rotulo();
        rNomePaiConj = new br.com.martinello.componentesbasicos.Rotulo();
        rNomeConj = new br.com.martinello.componentesbasicos.Rotulo();
        rDataNascConj = new br.com.martinello.componentesbasicos.Rotulo();
        rNomeMaeConj = new br.com.martinello.componentesbasicos.Rotulo();
        rotuloDocumento = new br.com.martinello.componentesbasicos.Rotulo();
        rotuloNaturalidadeConj = new br.com.martinello.componentesbasicos.Rotulo();
        rotuloNomePaiConj = new br.com.martinello.componentesbasicos.Rotulo();
        rotuloNomeConj = new br.com.martinello.componentesbasicos.Rotulo();
        rotuloNomeMaeConj = new br.com.martinello.componentesbasicos.Rotulo();
        cdNascConj = new br.com.martinello.componentesbasicos.CampoData();
        cccCpfConjuge = new br.com.martinello.componentesbasicos.CampoCpfCnpj();
        pDadosPessoais = new br.com.martinello.componentesbasicos.paineis.Painel();
        rSexo = new br.com.martinello.componentesbasicos.Rotulo();
        rNomePai = new br.com.martinello.componentesbasicos.Rotulo();
        rEstadoCivil = new br.com.martinello.componentesbasicos.Rotulo();
        clsSexo = new br.com.martinello.componentesbasicos.CampoListaSimples();
        clsEstadoCivil = new br.com.martinello.componentesbasicos.CampoListaSimples();
        rDataNascimento = new br.com.martinello.componentesbasicos.Rotulo();
        cdNasc = new br.com.martinello.componentesbasicos.CampoData();
        rNaturalidade = new br.com.martinello.componentesbasicos.Rotulo();
        rotuloNomePai = new br.com.martinello.componentesbasicos.Rotulo();
        rNomeMae = new br.com.martinello.componentesbasicos.Rotulo();
        rotuloNomeMae = new br.com.martinello.componentesbasicos.Rotulo();
        rotuloNaturalidade = new br.com.martinello.componentesbasicos.Rotulo();
        pDadosRendaMoradia = new br.com.martinello.componentesbasicos.paineis.Painel();
        pDadosRenda = new br.com.martinello.componentesbasicos.paineis.Painel();
        rRenda = new br.com.martinello.componentesbasicos.Rotulo();
        rRendaCompl = new br.com.martinello.componentesbasicos.Rotulo();
        rDespesasMoradia = new br.com.martinello.componentesbasicos.Rotulo();
        rDespesasMensal = new br.com.martinello.componentesbasicos.Rotulo();
        rNumeroDependentes = new br.com.martinello.componentesbasicos.Rotulo();
        rValorPatrimonio = new br.com.martinello.componentesbasicos.Rotulo();
        ciNumeroDependentes = new br.com.martinello.componentesbasicos.CampoInteiro();
        cvRenda = new br.com.martinello.componentesbasicos.CampoValor();
        cvRendaCompl = new br.com.martinello.componentesbasicos.CampoValor();
        cvDespesasMoradia = new br.com.martinello.componentesbasicos.CampoValor();
        cvDespesasMensal = new br.com.martinello.componentesbasicos.CampoValor();
        cvValorParimonio = new br.com.martinello.componentesbasicos.CampoValor();
        rDescricao = new br.com.martinello.componentesbasicos.Rotulo();
        rotuloDescricao = new br.com.martinello.componentesbasicos.Rotulo();
        pDadosResidencia = new br.com.martinello.componentesbasicos.paineis.Painel();
        rTipoMoradia = new br.com.martinello.componentesbasicos.Rotulo();
        rDataMoradia = new br.com.martinello.componentesbasicos.Rotulo();
        clsTipoMorradia = new br.com.martinello.componentesbasicos.CampoListaSimples();
        cdMoradia = new br.com.martinello.componentesbasicos.CampoData();
        ppReferencia = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        pTableReferencias = new br.com.martinello.componentesbasicos.paineis.Painel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpReferencias = new br.com.martinello.componentesbasicos.TabelaPadrao();
        ppConsultas = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        pTableConsultas = new br.com.martinello.componentesbasicos.paineis.Painel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpConsulta = new br.com.martinello.componentesbasicos.TabelaPadrao();
        ppDadosComerciais = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        pTableDadosComerciais = new br.com.martinello.componentesbasicos.paineis.Painel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tpDadosComerciais = new br.com.martinello.componentesbasicos.TabelaPadrao();
        ppHistorico = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        jScrollPane5 = new javax.swing.JScrollPane();
        tpHistorico = new br.com.martinello.componentesbasicos.TabelaPadrao();
        ppObservacao = new br.com.martinello.componentesbasicos.paineis.PainelPadrao();
        jScrollPane6 = new javax.swing.JScrollPane();
        tpObservacao = new br.com.martinello.componentesbasicos.TabelaPadrao();
        pCliente = new br.com.martinello.componentesbasicos.paineis.Painel();
        botao1 = new br.com.martinello.componentesbasicos.Botao();
        botao2 = new br.com.martinello.componentesbasicos.Botao();
        
        ppClienteAba.setLayout(new java.awt.BorderLayout());
        
        rotulo2.setText("Id. Cliente:");
        
        rotulo3.setText("Tipo:");
        
        rotulo4.setText("Cpf/Cnpj:");
        
        csRazaoSocial.setEditable(false);
        
        rotulo6.setText("Razão Social:");
        
        csNomeFantazia.setEditable(false);
        
        rotulo7.setText("Nome Fantazia:");
        
        csEmail.setEditable(false);
        
        rotulo8.setText("Email:");
        
        rotulo9.setText("Telefone:");
        
        rotulo10.setText("Celular:");
        
        csContato.setEditable(false);
        
        rotulo11.setText("Contato:");
        
        rotulo14.setText("Negativado:");
        
        clsTipoPessoa.setToolTipText("Fisica\nJurídica");
        
        clsNegativado.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Não", "Baixado"}));
        clsNegativado.setEnabled(false);
        
        cccCpfCnpj.setEditable(false);
        
        ctTelefone.setEditable(false);
        
        ctCelular.setEditable(false);
        
        ciCodCli.setEditable(false);
        
        rotulo1.setText("Situação:");
        
        clsSitCli.setDescricaoRotulo("");
        clsSitCli.setEnabled(false);
        
        javax.swing.GroupLayout ppClienteLayout = new javax.swing.GroupLayout(ppCliente);
        ppCliente.setLayout(ppClienteLayout);
        ppClienteLayout.setHorizontalGroup(
                ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ppClienteLayout.createSequentialGroup()
                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ppClienteLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rotulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotulo8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotulo9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotulo10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotulo11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotulo14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cccCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(csRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(csNomeFantazia, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(csEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ctTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ctCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(csContato, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(clsNegativado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(ciCodCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(clsTipoPessoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                                        .addGroup(ppClienteLayout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(rotulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(clsSitCli, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(645, Short.MAX_VALUE))
        );
        ppClienteLayout.setVerticalGroup(
                ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ppClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rotulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ciCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rotulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(clsTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rotulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cccCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rotulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(csRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rotulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(csNomeFantazia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rotulo8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(csEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rotulo9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ctTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rotulo10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ctCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rotulo11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(csContato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rotulo14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(clsNegativado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ppClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rotulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(clsSitCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(388, Short.MAX_VALUE))
        );
        paCliente.setPreferredSize(new java.awt.Dimension(1024, 350));
        paCliente.addTab("Cliente", ppCliente);
        
        ppEndereco.setLayout(new java.awt.BorderLayout());
        
        pTableEndereco.setLayout(new java.awt.BorderLayout());
        
        tpEndereco.setModel(otmClienteEndereco);
        jScrollPane1.setViewportView(tpEndereco);
        
        pTableEndereco.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        
        ppEndereco.add(pTableEndereco, java.awt.BorderLayout.CENTER);
        
        paCliente.addTab("Endereços", ppEndereco);
        
        ppDadosCompl.setLayout(new java.awt.BorderLayout());
        
        pDadosCompl.setPreferredSize(new java.awt.Dimension(1024, 350));
        pDadosCompl.setLayout(new java.awt.BorderLayout());
        
        PDadosConjugue.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Cônjuge"));
        
        rCpf.setText("CPF:");
        
        rNaturalidaConj.setText("Naturalidade:");
        
        rDocumento.setText("Documento:");
        
        rNomePaiConj.setText("Nome Pai:");
        
        rNomeConj.setText("Nome:");
        
        rDataNascConj.setText("Data Nascimento:");
        
        rNomeMaeConj.setText("Nome Mãe:");
        
        rotuloDocumento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        
        rotuloNaturalidadeConj.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        
        rotuloNomePaiConj.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        
        rotuloNomeConj.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        
        rotuloNomeMaeConj.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        
        cdNascConj.setEditable(false);
        
        cccCpfConjuge.setEditable(false);
        
        javax.swing.GroupLayout PDadosConjugueLayout = new javax.swing.GroupLayout(PDadosConjugue);
        PDadosConjugue.setLayout(PDadosConjugueLayout);
        PDadosConjugueLayout.setHorizontalGroup(
                PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PDadosConjugueLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PDadosConjugueLayout.createSequentialGroup()
                                                .addComponent(rDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rotuloDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PDadosConjugueLayout.createSequentialGroup()
                                                .addComponent(rCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cccCpfConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PDadosConjugueLayout.createSequentialGroup()
                                                .addComponent(rNaturalidaConj, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rotuloNaturalidadeConj, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PDadosConjugueLayout.createSequentialGroup()
                                                .addComponent(rNomePaiConj, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rotuloNomePaiConj, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)
                                .addGroup(PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(rNomeConj, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                        .addComponent(rDataNascConj, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                        .addComponent(rNomeMaeConj, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cdNascConj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rotuloNomeMaeConj, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rotuloNomeConj, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(389, Short.MAX_VALUE))
        );
        PDadosConjugueLayout.setVerticalGroup(
                PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PDadosConjugueLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PDadosConjugueLayout.createSequentialGroup()
                                                .addGroup(PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cccCpfConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotuloDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rNaturalidaConj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotuloNaturalidadeConj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rNomePaiConj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotuloNomePaiConj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(PDadosConjugueLayout.createSequentialGroup()
                                                .addGroup(PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rNomeConj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotuloNomeConj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(33, 33, 33)
                                                .addGroup(PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rDataNascConj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cdNascConj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(PDadosConjugueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rNomeMaeConj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotuloNomeMaeConj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(94, Short.MAX_VALUE))
        );
        
        pDadosCompl.add(PDadosConjugue, java.awt.BorderLayout.CENTER);
        
        pDadosPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        pDadosPessoais.setPreferredSize(new java.awt.Dimension(1040, 120));
        
        rSexo.setText("Sexo:");
        
        rNomePai.setText("Nome do Pai:");
        
        rEstadoCivil.setText("Estado Civil:");
        
        clsSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Masculino", "Feminino"}));
        clsSexo.setEnabled(false);
        
        clsEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"S - Solteiro(a)", "C - Casado(a)", "J - Separado(a) Judicialmente", "D - Divorciado(a)", "V - Viúvo(a)", "U - União estavel", "O - Outros"}));
        clsEstadoCivil.setEnabled(false);
        
        rDataNascimento.setText("Data Nascimento:");
        
        cdNasc.setEditable(false);
        
        rNaturalidade.setText("Naturalidade:");
        
        rotuloNomePai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        
        rNomeMae.setText("Nome Mãe:");
        
        rotuloNomeMae.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        
        rotuloNaturalidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        
        javax.swing.GroupLayout pDadosPessoaisLayout = new javax.swing.GroupLayout(pDadosPessoais);
        pDadosPessoais.setLayout(pDadosPessoaisLayout);
        pDadosPessoaisLayout.setHorizontalGroup(
                pDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pDadosPessoaisLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(pDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pDadosPessoaisLayout.createSequentialGroup()
                                                .addGroup(pDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(clsEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotuloNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)
                                                .addComponent(rNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rotuloNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pDadosPessoaisLayout.createSequentialGroup()
                                                .addComponent(clsSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cdNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rotuloNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(284, Short.MAX_VALUE))
        );
        pDadosPessoaisLayout.setVerticalGroup(
                pDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pDadosPessoaisLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pDadosPessoaisLayout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(pDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotuloNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pDadosPessoaisLayout.createSequentialGroup()
                                                .addComponent(rSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(clsEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pDadosPessoaisLayout.createSequentialGroup()
                                                .addGroup(pDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(clsSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cdNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rotuloNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rotuloNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 15, Short.MAX_VALUE))
        );
        
        pDadosCompl.add(pDadosPessoais, java.awt.BorderLayout.NORTH);
        
        ppDadosCompl.add(pDadosCompl, java.awt.BorderLayout.NORTH);
        
        pDadosRendaMoradia.setLayout(new java.awt.BorderLayout());
        
        pDadosRenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Renda"));
        pDadosRenda.setPreferredSize(new java.awt.Dimension(1024, 200));
        
        rRenda.setText("Renda:");
        
        rRendaCompl.setText("Renda Complementar");
        
        rDespesasMoradia.setText("Despesas Moradia:");
        
        rDespesasMensal.setText("Despesas Mensal:");
        
        rNumeroDependentes.setText("Número Dependentes:");
        
        rValorPatrimonio.setText("Valor Patrimônio:");
        
        ciNumeroDependentes.setEditable(false);
        ciNumeroDependentes.setDescricaoRotulo("");
        
        cvRenda.setEditable(false);
        
        cvRendaCompl.setEditable(false);
        
        cvDespesasMoradia.setEditable(false);
        
        cvDespesasMensal.setEditable(false);
        
        cvValorParimonio.setEditable(false);
        
        rDescricao.setText("Descrição:");
        
        rotuloDescricao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        
        javax.swing.GroupLayout pDadosRendaLayout = new javax.swing.GroupLayout(pDadosRenda);
        pDadosRenda.setLayout(pDadosRendaLayout);
        pDadosRendaLayout.setHorizontalGroup(
                pDadosRendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pDadosRendaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pDadosRendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(rRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rRendaCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rDespesasMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rDespesasMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rNumeroDependentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rValorPatrimonio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pDadosRendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ciNumeroDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cvRenda, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(cvRendaCompl, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(cvDespesasMoradia, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(cvDespesasMensal, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(cvValorParimonio, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGap(74, 74, 74)
                                .addComponent(rDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rotuloDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(343, Short.MAX_VALUE))
        );
        pDadosRendaLayout.setVerticalGroup(
                pDadosRendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pDadosRendaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pDadosRendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cvRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pDadosRendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rRendaCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cvRendaCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rotuloDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pDadosRendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rDespesasMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cvDespesasMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pDadosRendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rDespesasMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cvDespesasMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pDadosRendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rNumeroDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ciNumeroDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pDadosRendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rValorPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cvValorParimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(101, Short.MAX_VALUE))
        );
        
        pDadosRendaMoradia.add(pDadosRenda, java.awt.BorderLayout.CENTER);
        
        pDadosResidencia.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Residência"));
        pDadosResidencia.setPreferredSize(new java.awt.Dimension(1359, 50));
        
        rTipoMoradia.setText("Tipo:");
        
        rDataMoradia.setText("Data:");
        
        clsTipoMorradia.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"1 - Própria", "2 - Alugada", "3 - Financiada", "4 - Cessão", "5 - Outros"}));
        clsTipoMorradia.setEnabled(false);
        
        cdMoradia.setEditable(false);
        
        javax.swing.GroupLayout pDadosResidenciaLayout = new javax.swing.GroupLayout(pDadosResidencia);
        pDadosResidencia.setLayout(pDadosResidenciaLayout);
        pDadosResidenciaLayout.setHorizontalGroup(
                pDadosResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pDadosResidenciaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rTipoMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clsTipoMorradia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178)
                                .addComponent(rDataMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cdMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(609, Short.MAX_VALUE))
        );
        pDadosResidenciaLayout.setVerticalGroup(
                pDadosResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pDadosResidenciaLayout.createSequentialGroup()
                                .addGroup(pDadosResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rTipoMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rDataMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(clsTipoMorradia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cdMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 4, Short.MAX_VALUE))
        );
        
        pDadosRendaMoradia.add(pDadosResidencia, java.awt.BorderLayout.NORTH);
        
        ppDadosCompl.add(pDadosRendaMoradia, java.awt.BorderLayout.CENTER);
        
        paCliente.addTab("Dados Complementares", ppDadosCompl);
        
        ppReferencia.setLayout(new java.awt.BorderLayout());
        
        pTableReferencias.setLayout(new java.awt.BorderLayout());
        
        tpReferencias.setModel(otmReferencias);
        jScrollPane2.setViewportView(tpReferencias);
        
        pTableReferencias.add(jScrollPane2, java.awt.BorderLayout.CENTER);
        
        ppReferencia.add(pTableReferencias, java.awt.BorderLayout.CENTER);
        
        paCliente.addTab("Referências", ppReferencia);
        
        ppConsultas.setLayout(new java.awt.BorderLayout());
        
        pTableConsultas.setLayout(new java.awt.BorderLayout());
        
        tpConsulta.setModel(otmConsulta);
        jScrollPane3.setViewportView(tpConsulta);
        
        pTableConsultas.add(jScrollPane3, java.awt.BorderLayout.CENTER);
        
        ppConsultas.add(pTableConsultas, java.awt.BorderLayout.CENTER);
        
        paCliente.addTab("Consultas", ppConsultas);
        
        ppDadosComerciais.setLayout(new java.awt.BorderLayout());
        
        pTableDadosComerciais.setLayout(new java.awt.BorderLayout());
        
        tpDadosComerciais.setModel(otmDadosComerciais);
        jScrollPane4.setViewportView(tpDadosComerciais);
        
        pTableDadosComerciais.add(jScrollPane4, java.awt.BorderLayout.CENTER);
        
        ppDadosComerciais.add(pTableDadosComerciais, java.awt.BorderLayout.CENTER);
        
        paCliente.addTab("Dados Comerciais", ppDadosComerciais);
        ppHistorico.setLayout(new java.awt.BorderLayout());
        tpHistorico.setModel(otmHistorico);
        jScrollPane5.setViewportView(tpHistorico);
        ppHistorico.add(jScrollPane5, java.awt.BorderLayout.CENTER);        
        paCliente.addTab("Histórico", ppHistorico);
        
        ppObservacao.setLayout(new java.awt.BorderLayout());
        tpObservacao.setModel(otmObservacao);
        tpObservacao.setPreferredSize(new java.awt.Dimension(0, 100));
        jScrollPane6.setViewportView(tpObservacao);
        jScrollPane6.setPreferredSize(new java.awt.Dimension(0, 100));
        ppObservacao.add(jScrollPane6, java.awt.BorderLayout.CENTER);    
        ppObservacao.setPreferredSize(new java.awt.Dimension(100, 100));
        paCliente.addTab("Observações", ppObservacao);
        
       ppClienteAba.add(paCliente, java.awt.BorderLayout.CENTER);
        
        //pCliente.setPreferredSize(new java.awt.Dimension(1345, 30));
        
        botao1.setText("Cancelar");
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });
        
        botao2.setText("Salvar");
        botao2.setEnabled(false);
        
//        javax.swing.GroupLayout pClienteLayout = new javax.swing.GroupLayout(pCliente);
//        pCliente.setLayout(pClienteLayout);
//        pClienteLayout.setHorizontalGroup(
//                pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pClienteLayout.createSequentialGroup()
//                                .addContainerGap(534, Short.MAX_VALUE)
//                                .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(594, 594, 594))
//        );
//        pClienteLayout.setVerticalGroup(
//                pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pClienteLayout.createSequentialGroup()
//                                .addGap(0, 9, Short.MAX_VALUE)
//                                .addGroup(pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
//        );
        
//        ppClienteAba.add(pCliente, java.awt.BorderLayout.SOUTH);
//        
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//        this.setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGap(0, 1364, Short.MAX_VALUE)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                .addGroup(layout.createSequentialGroup()
//                                        .addGap(0, 0, Short.MAX_VALUE)
//                                        .addComponent(ppClienteAba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addGap(0, 0, Short.MAX_VALUE)))
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGap(0, 750, Short.MAX_VALUE)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                .addGroup(layout.createSequentialGroup()
//                                        .addGap(0, 0, Short.MAX_VALUE)
//                                        .addComponent(ppClienteAba, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addGap(0, 0, Short.MAX_VALUE)))
//       );
    }// </editor-fold>//GEN-END:initComponents

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed

    }//GEN-LAST:event_botao1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.componentesbasicos.paineis.Painel PDadosConjugue;
    private br.com.martinello.componentesbasicos.Botao botao1;
    private br.com.martinello.componentesbasicos.Botao botao2;
    private br.com.martinello.componentesbasicos.CampoCpfCnpj cccCpfCnpj;
    private br.com.martinello.componentesbasicos.CampoCpfCnpj cccCpfConjuge;
    private br.com.martinello.componentesbasicos.CampoData cdMoradia;
    private br.com.martinello.componentesbasicos.CampoData cdNasc;
    private br.com.martinello.componentesbasicos.CampoData cdNascConj;
    private br.com.martinello.componentesbasicos.CampoInteiro ciCodCli;
    private br.com.martinello.componentesbasicos.CampoInteiro ciNumeroDependentes;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsEstadoCivil;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsNegativado;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsSexo;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsSitCli;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsTipoMorradia;
    private br.com.martinello.componentesbasicos.CampoListaSimples clsTipoPessoa;
    private br.com.martinello.componentesbasicos.CampoString csContato;
    private br.com.martinello.componentesbasicos.CampoString csEmail;
    private br.com.martinello.componentesbasicos.CampoString csNomeFantazia;
    private br.com.martinello.componentesbasicos.CampoString csRazaoSocial;
    private br.com.martinello.componentesbasicos.CampoTelefone ctCelular;
    private br.com.martinello.componentesbasicos.CampoTelefone ctTelefone;
    private br.com.martinello.componentesbasicos.CampoValor cvDespesasMensal;
    private br.com.martinello.componentesbasicos.CampoValor cvDespesasMoradia;
    private br.com.martinello.componentesbasicos.CampoValor cvRenda;
    private br.com.martinello.componentesbasicos.CampoValor cvRendaCompl;
    private br.com.martinello.componentesbasicos.CampoValor cvValorParimonio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private br.com.martinello.componentesbasicos.paineis.Painel pCliente;
    private br.com.martinello.componentesbasicos.paineis.Painel pDadosCompl;
    private br.com.martinello.componentesbasicos.paineis.Painel pDadosPessoais;
    private br.com.martinello.componentesbasicos.paineis.Painel pDadosRenda;
    private br.com.martinello.componentesbasicos.paineis.Painel pDadosRendaMoradia;
    private br.com.martinello.componentesbasicos.paineis.Painel pDadosResidencia;
    private br.com.martinello.componentesbasicos.paineis.Painel pTableConsultas;
    private br.com.martinello.componentesbasicos.paineis.Painel pTableDadosComerciais;
    private br.com.martinello.componentesbasicos.paineis.Painel pTableEndereco;
    private br.com.martinello.componentesbasicos.paineis.Painel pTableReferencias;
    private br.com.martinello.componentesbasicos.paineis.PainelAba paCliente;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppCliente;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppClienteAba;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppConsultas;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppDadosComerciais;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppDadosCompl;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppEndereco;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppHistorico;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppObservacao;
    private br.com.martinello.componentesbasicos.paineis.PainelPadrao ppReferencia;
    private br.com.martinello.componentesbasicos.Rotulo rCpf;
    private br.com.martinello.componentesbasicos.Rotulo rDataMoradia;
    private br.com.martinello.componentesbasicos.Rotulo rDataNascConj;
    private br.com.martinello.componentesbasicos.Rotulo rDataNascimento;
    private br.com.martinello.componentesbasicos.Rotulo rDescricao;
    private br.com.martinello.componentesbasicos.Rotulo rDespesasMensal;
    private br.com.martinello.componentesbasicos.Rotulo rDespesasMoradia;
    private br.com.martinello.componentesbasicos.Rotulo rDocumento;
    private br.com.martinello.componentesbasicos.Rotulo rEstadoCivil;
    private br.com.martinello.componentesbasicos.Rotulo rNaturalidaConj;
    private br.com.martinello.componentesbasicos.Rotulo rNaturalidade;
    private br.com.martinello.componentesbasicos.Rotulo rNomeConj;
    private br.com.martinello.componentesbasicos.Rotulo rNomeMae;
    private br.com.martinello.componentesbasicos.Rotulo rNomeMaeConj;
    private br.com.martinello.componentesbasicos.Rotulo rNomePai;
    private br.com.martinello.componentesbasicos.Rotulo rNomePaiConj;
    private br.com.martinello.componentesbasicos.Rotulo rNumeroDependentes;
    private br.com.martinello.componentesbasicos.Rotulo rRenda;
    private br.com.martinello.componentesbasicos.Rotulo rRendaCompl;
    private br.com.martinello.componentesbasicos.Rotulo rSexo;
    private br.com.martinello.componentesbasicos.Rotulo rTipoMoradia;
    private br.com.martinello.componentesbasicos.Rotulo rValorPatrimonio;
    private br.com.martinello.componentesbasicos.Rotulo rotulo1;
    private br.com.martinello.componentesbasicos.Rotulo rotulo10;
    private br.com.martinello.componentesbasicos.Rotulo rotulo11;
    private br.com.martinello.componentesbasicos.Rotulo rotulo14;
    private br.com.martinello.componentesbasicos.Rotulo rotulo2;
    private br.com.martinello.componentesbasicos.Rotulo rotulo3;
    private br.com.martinello.componentesbasicos.Rotulo rotulo4;
    private br.com.martinello.componentesbasicos.Rotulo rotulo6;
    private br.com.martinello.componentesbasicos.Rotulo rotulo7;
    private br.com.martinello.componentesbasicos.Rotulo rotulo8;
    private br.com.martinello.componentesbasicos.Rotulo rotulo9;
    private br.com.martinello.componentesbasicos.Rotulo rotuloDescricao;
    private br.com.martinello.componentesbasicos.Rotulo rotuloDocumento;
    private br.com.martinello.componentesbasicos.Rotulo rotuloNaturalidade;
    private br.com.martinello.componentesbasicos.Rotulo rotuloNaturalidadeConj;
    private br.com.martinello.componentesbasicos.Rotulo rotuloNomeConj;
    private br.com.martinello.componentesbasicos.Rotulo rotuloNomeMae;
    private br.com.martinello.componentesbasicos.Rotulo rotuloNomeMaeConj;
    private br.com.martinello.componentesbasicos.Rotulo rotuloNomePai;
    private br.com.martinello.componentesbasicos.Rotulo rotuloNomePaiConj;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpConsulta;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpDadosComerciais;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpEndereco;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpHistorico;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpObservacao;
    private br.com.martinello.componentesbasicos.TabelaPadrao tpReferencias;

    // End of variables declaration//GEN-END:variables
    public boolean visualizarCliente(String sCodFil, int codCli) throws ErroSistemaException {
        resultado = false;
        try {
            consultaClienteControl = new ConsultaClienteControl();
            consultaCliente = new ConsultaClienteModel();
            consultaCliente = consultaClienteControl.ConsultarCliente(sCodFil, codCli);
            csRazaoSocial.setString(consultaCliente.getCliente().getNomeRazaoSocial());
            ciCodCli.setInteger(consultaCliente.getCliente().getIdPessoa());
            cccCpfCnpj.setText(consultaCliente.getCliente().getCpf());
            csEmail.setString(consultaCliente.getCliente().getEmail());
            ctTelefone.setText(consultaCliente.getCliente().getNumeroTel());
            ctCelular.setText(consultaCliente.getCliente().getNumeroCelular());
            clsSitCli.getModel().setSelectedItem(consultaCliente.getCliente().getSituacao());
            if (consultaCliente.getCliente().getNegativacao().equalsIgnoreCase("B")) {
                clsNegativado.setInt(1);
            } else {
                clsNegativado.setInt(0);
            }
            if (consultaCliente.getCliente().getSexo().equalsIgnoreCase("M")) {
                clsSexo.setInt(0);
            } else {
                clsSexo.setInt(1);
            }
            if (consultaCliente.getCliente().getTipoPessoa().equalsIgnoreCase("F")) {
                clsTipoPessoa.setInt(0);
            } else {
                clsTipoPessoa.setInt(1);
            }
            cdNasc.setDate(consultaCliente.getCliente().getDataNascimento());
            rotuloNomePai.setText(consultaCliente.getCliente().getNomeDoPai());
            rotuloNomeMae.setText(consultaCliente.getCliente().getNomeDaMae());
            rotuloNaturalidade.setText(consultaCliente.getCliente().getNaturalidade());
            
            cccCpfConjuge.setText(consultaCliente.getClienteConjuge().getCpf());
            cdNascConj.setDate(consultaCliente.getClienteConjuge().getDataNascimento());
            rotuloNomePaiConj.setText(consultaCliente.getClienteConjuge().getNomeDoPai());
            rotuloNomeMaeConj.setText(consultaCliente.getClienteConjuge().getNomeDaMae());
            rotuloNaturalidadeConj.setText(consultaCliente.getClienteConjuge().getNaturalidade());
            
            cdMoradia.setDate(consultaCliente.getDataResidencia());
            
            cvRenda.setDouble(consultaCliente.getRenda());
            cvRendaCompl.setDouble(consultaCliente.getRendaComplementar());
            rotuloDescricao.setText(consultaCliente.getDescRendaComplementar());
            cvDespesasMoradia.setDouble(consultaCliente.getDespesasMoradia());
            cvDespesasMensal.setDouble(consultaCliente.getDespesasMensal());
            cvValorParimonio.setDouble(consultaCliente.getValorPatrimnonio());
            otmClienteEndereco.setData(consultaCliente.getlEnderecos());
            
            otmClienteEndereco.fireTableDataChanged();
            if (tpEndereco.getRowCount() > 0) {
                tpEndereco.packAll();
                tpEndereco.addRowSelectionInterval(tpEndereco.convertRowIndexToView(0), tpEndereco.convertRowIndexToView(0));
                tpEndereco.grabFocus();
            }
            otmReferencias.setData(consultaCliente.getlReferencias());
            otmReferencias.fireTableDataChanged();
            if (tpReferencias.getRowCount() > 0) {
                tpReferencias.packAll();
                tpReferencias.addRowSelectionInterval(tpReferencias.convertRowIndexToView(0), tpReferencias.convertRowIndexToView(0));
                tpReferencias.grabFocus();
            }
            otmObservacao.setData(consultaCliente.getlObservacoes());
            otmObservacao.fireTableDataChanged();
            if (tpObservacao.getRowCount() > 0) {
                tpObservacao.packAll();
                tpObservacao.addRowSelectionInterval(tpObservacao.convertRowIndexToView(0), tpObservacao.convertRowIndexToView(0));
                tpObservacao.grabFocus();
            }
            otmConsulta.setData(consultaCliente.getlConsulta());
            otmConsulta.fireTableDataChanged();
            if (tpConsulta.getRowCount() > 0) {
                tpConsulta.packAll();
                tpConsulta.addRowSelectionInterval(tpConsulta.convertRowIndexToView(0), tpConsulta.convertRowIndexToView(0));
                tpConsulta.grabFocus();
            }
            otmDadosComerciais.setData(consultaCliente.getlDadosComericiais());
            otmDadosComerciais.fireTableDataChanged();
            if (tpDadosComerciais.getRowCount() > 0) {
                tpDadosComerciais.packAll();
                tpDadosComerciais.addRowSelectionInterval(tpDadosComerciais.convertRowIndexToView(0), tpDadosComerciais.convertRowIndexToView(0));
                tpDadosComerciais.grabFocus();
            }
            resultado = true;
            
        } catch (ErroSistemaException ex) {
            throw new ErroSistemaException(ex.getMessage(), ex.getCause());
        }
        return resultado;
    }
}
