/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.componentesbasicos.consulta;

import br.com.martinello.componentesbasicos.paineis.Painel;
import br.com.martinello.util.filtro.Filtro;
import br.com.martinello.util.filtro.Periodo;

/**
 *
 * @author Sidnei
 */
public class CampoNumeroConsulta extends Painel {

    /**
     * Creates new form CampoStringConsulta
     */
    public CampoNumeroConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ciNumeroInicial = new br.com.martinello.componentesbasicos.CampoInteiro();
        rSeparador = new br.com.martinello.componentesbasicos.Rotulo();
        ciNumeroFinal = new br.com.martinello.componentesbasicos.CampoInteiro();

        setLayout(new java.awt.BorderLayout());

        ciNumeroInicial.setText("0");
        ciNumeroInicial.setPreferredSize(new java.awt.Dimension(99, 23));
        add(ciNumeroInicial, java.awt.BorderLayout.WEST);

        rSeparador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSeparador.setText("-");
        add(rSeparador, java.awt.BorderLayout.CENTER);

        ciNumeroFinal.setText("0");
        ciNumeroFinal.setPreferredSize(new java.awt.Dimension(99, 23));
        add(ciNumeroFinal, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.martinello.componentesbasicos.CampoInteiro ciNumeroFinal;
    private br.com.martinello.componentesbasicos.CampoInteiro ciNumeroInicial;
    private br.com.martinello.componentesbasicos.Rotulo rSeparador;
    // End of variables declaration//GEN-END:variables

    public Long getNumeroInicial() {
        return ciNumeroInicial.getLong();
    }

    public Long getNumeroFinal() {
        return ciNumeroFinal.getLong();
    }

    public Filtro getFiltro(String campo, String formato) {
        if (getNumeroInicial() != null && getNumeroFinal() != null && getNumeroInicial() > 0l && getNumeroFinal() > 0l) {
            return new Filtro(campo, formato, Filtro.PERIODO, new Periodo(getNumeroInicial(), getNumeroFinal()));
        } else if (getNumeroInicial() != null && getNumeroInicial() > 0l) {
            return new Filtro(campo, formato, Filtro.MAIOR, getNumeroInicial());
        } else if (getNumeroFinal() != null && getNumeroFinal() > 0l) {
            return new Filtro(campo, formato, Filtro.MENOR, getNumeroFinal());
        } else {
            return new Filtro(campo, formato, Filtro.PERIODO, null);
        }
    }
}
